; ability constants
; indexes for:
; - AbilityNames (see data/abilities/names.asm)
; - AbilityDescriptions (see data/abilities/descriptions.asm)
	const_def
	const NO_ABILITY
	const DISTANCE
	const DRIZZLE
	const SPEED_BOOST
	const BATTLE_ARMOR
	const STURDY
	const DAMP
	const LIMBER
	const SAND_VEIL
	const STATIC
	const VOLT_ABSORB
	const WATER_ABSORB
	const OBLIVIOUS
	const HISOUTEN
	const CONCENTRATE
	const INSOMNIA
	const IMMUNITY
	const FLASH_FIRE
	const MONOCHANNEL
	const OWN_TEMPO
	const GATE_KEEPER
	const INTIMIDATE
	const CORNER_GAP
	const LEVITATE
	const EFFECT_TRIAGE
	const SYNCHRONIZE
	const HAKUREI_MIKO
	const NATURAL_CURE
	const LIGHTNING_ROD
	const SERENE_GRACE
	const SWIFT_SWIM
	const CHLOROPHYLL
	const ROLLCALL
	const TRACE
	const RAW_POWER
	const SEEPING_TOXIN
	const INNER_FOCUS
	const FIRE_VEIL
	const WATER_VEIL
	const ELECTRO_WAVE
	const SOUNDPROOF
	const RAIN_DISH
	const SAND_STREAM
	const PRESSURE
	const ICE_WALL
	const EARLY_BIRD
	const FLAME_BODY
	const RUN_AWAY
	const KEEN_EYE
	const HI_STRENGTH
	const PICKUP
	const HUSTLE
	const CUTE_CHARM
	const COLLECTOR
	const SHED_SKIN
	const GUTS
	const SPRING_CHARM
	const MISFORTUNATE
	const OVERGROW
	const BLAZE
	const TORRENT
	const PUREHEART
	const HARD_HEAD
	const DROUGHT
	const ARENA_TRAP
	const VITAL_SPIRIT
	const MAGIC_BARRIER
	const GUARD_ARMOR
	const NEARSIGHTED
	const MOTOR_DRIVE
	const RIVALRY
	const STEADFAST
	const SNOW_CLOAK
	const GLUTTONY
	const ANGER_POINT
	const UNBURDEN
	const DRY_SKIN
	const DOWNLOAD
	const IRON_FIST
	const POISON_HEAL
	const ADAPTABILITY
	const SKILL_LINK
	const HYDRATION
	const SOLAR_POWER
	const QUICK_FEET
	const SNIPER
	const MAGIC_GUARD
	const NO_GUARD
	const TECHNICIAN
	const LEAF_GUARD
	const MOLD_BREAKER
	const SUPER_LUCK
	const SURPRISE
	const ANTICIPATION
	const ALERT
	const UNAWARE
	const POWER_BOOST
	const FILTER
	const SCRAPPY
	const ICE_BODY
	const SOLID_ROCK
	const SNOW_WARNING
	const HONEY_GATHER
	const FRISK
	const RECKLESS
	const SWIPE
	const STRATEGIC
	const CONTRARY
	const UNNERVE
	const DEFIANT
	const CURSED_BODY
	const FRAGILITY
	const LIGHT_METAL
	const DECOY_GUARD
	const HARVEST
	const MOODY
	const OVERCOAT
	const POISON_TOUCH
	const REGENERATOR
	const DOME_BODY
	const SAND_RUSH
	const WONDER_SKIN
	const ANALYTIC
	const RECOLLECTOR
	const GUARDPASS
	const MOXIE
	const JUSTIFIED
	const RATTLED
	const MAGIC_BOUNCE
	const SAP_ABSORB
	const PRANKSTER
	const SAND_FORCE
	const ARMOR_LAYER
	const BULLETPROOF
	const COMPETITIVE
	const SOUL_POWER
	const SHARP_CLAWS
	const PURITY
	const TROOPERS
	const BERSERK
	const ICY_FEET
	const GALVANIZE
	const CORROSION
	const TIME_COUNTER
	const COMBAT_LOCK
	const NEUTRALIZATION
	const POISON_GUARD
	const QUICK_DRAW
	const RAZOR_BLADE
	const PERISH_BODY
	const SCREEN_REMOVAL
	const LINGER_POWER
	const CLEAN_CUTTER
	const SKILL_CANCEL
	const MINDS_EYE
DEF NUM_ABILITIES EQU const_value
