; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animation_pointers.asm)
	const_def
	const NO_MOVE      ; $00
	const ACROBATICS   ; $01
	const KARATE_CHOP  ; $02
	const DUAL_SHOT  ; $03
	const AERIAL_ACE   ; $04
	const POISON_CLAW  ; $05
	const PAY_DAY      ; $06
	const FIRE_PUNCH   ; $07
	const ICE_PUNCH    ; $08
	const THUNDERPUNCH ; $09
	const SCRATCH      ; $0a
	const CROSS_EYE    ; $0b
	const NIGHT_SLASH  ; $0c
	const AIR_SLASH    ; $0d
	const SWORDS_DANCE ; $0e
	const CUT          ; $0f
	const GUST         ; $10
	const WING_ATTACK  ; $11
	const SUCKER_PUNCH ; $12
	const FLY          ; $13
	const ENERGY_LIGHT ; $14
	const VOLT_SWITCH  ; $15
	const VINE_WHIP    ; $16
	const STOMP        ; $17
	const DOUBLE_KICK  ; $18
	const FLARE_OUT  ; $19
	const STONE_BREAK   ; $1a
	const FOCUS_BLAST  ; $1b
	const POISON_NAIL ; $1c
	const HEADBUTT     ; $1d
	const BLADE_THROW  ; $1e
	const TRICK        ; $1f
	const HEX          ; $20
	const TACKLE       ; $21
	const BODY_SLAM    ; $22
	const FANG_SHOT         ; $23
	const VENOM_POOL    ; $24
	const THRASH       ; $25
	const DOUBLE_EDGE  ; $26
	const HAIL         ; $27
	const PAPER_THROW ; $28
	const CHARGE_OUT       ; $29
	const PIN_BARRAGE  ; $2a
	const LEER         ; $2b
	const BITE         ; $2c
	const GROWL        ; $2d
	const ROAR         ; $2e
	const SING         ; $2f
	const SUPERSONIC   ; $30
	const SONIC_BOOM   ; $31
	const DISABLE      ; $32
	const POISON_TEARS         ; $33
	const EMBER        ; $34
	const FLAME_SHOOT ; $35
	const CALM_MIND    ; $36
	const WATER_GUN    ; $37
	const HYDRO_PUMP   ; $38
	const SURF         ; $39
	const ICE_BEAM     ; $3a
	const BLIZZARD     ; $3b
	const PSYBEAM      ; $3c
	const BUBBLE_BEAM  ; $3d
	const STAR_BLAST  ; $3e
	const POWER_BEAM   ; $3f
	const FEATHER_JAB         ; $40
	const ARM_THRUST   ; $41
	const COLOR_FIST ; $42
	const LOW_KICK     ; $43
	const COUNTER      ; $44
	const SEISMIC_TOSS ; $45
	const STRENGTH     ; $46
	const ABSORB       ; $47
	const MEGA_DRAIN   ; $48
	const LEECH_SEED   ; $49
	const GROWTH       ; $4a
	const RAZOR_LEAF   ; $4b
	const FLOWER_SHOOT   ; $4c
	const POISONPOWDER ; $4d
	const STUN_SPORE   ; $4e
	const SLEEP_POWDER ; $4f
	const BATTLE_CHANT  ; $50
	const JAMMING  ; $51
	const TOXIN_SHOT  ; $52
	const FIRE_SPIN    ; $53
	const THUNDERSHOCK ; $54
	const THUNDERBOLT  ; $55
	const THUNDER_WAVE ; $56
	const THUNDER      ; $57
	const ROCK_BULLET   ; $58
	const EARTHQUAKE   ; $59
	const AVALANCHE    ; $5a
	const DIG          ; $5b
	const TOXIC        ; $5c
	const PSYSHOT    ; $5d
	const MANA_BURST    ; $5e
	const HYPNOSIS     ; $5f
	const HONE_TOOLS   ; $60
	const LEAF_STORM      ; $61
	const QUICK_ATTACK ; $62
	const FIRE_LAUNCH         ; $63
	const TELEPORT     ; $64
	const NIGHT_SHADE  ; $65
	const ECHO_RAVE ; $66
	const SCREECH      ; $67
	const DOUBLE_TEAM  ; $68
	const RECOVER      ; $69
	const ROCK_BLAST   ; $6a
	const MINIMIZE     ; $6b
	const SMOKESCREEN  ; $6c
	const CONFUSE_RAY  ; $6d
	const AQUA_CUT    ; $6e
	const DEFENSE_CURL ; $6f
	const BARRIER      ; $70
	const LIGHT_SCREEN ; $71
	const HAZE         ; $72
	const REFLECT      ; $73
	const FOCUS_ENERGY ; $74
	const STAR_CANNON ; $75
	const METRONOME    ; $76
	const SCALD        ; $77
	const TRICK_ROOM   ; $78
	const SKILL_SWAP   ; $79
	const LICK         ; $7a
	const GUNK_SHOT    ; $7b
	const VENOSHOCK    ; $7c
	const EARTH_POWER  ; $7d
	const HELLBLAZE   ; $7e
	const WATERFALL    ; $7f
	const ICICLE_CRASH ; $80
	const SWIFT        ; $81
	const IRON_HEAD    ; $82
	const ICICLE_SPEAR ; $83
	const BULLDOZE     ; $84
	const AMNESIA      ; $85
	const AURA_WAVE        ; $86
	const FRESH_SNACK  ; $87
	const JUMP_KICK ; $88
	const GLARE        ; $89
	const DREAM_EATER  ; $8a
	const POISON_JAB   ; $8b
	const STEEL_FIST ; $8c
	const LEECH_LIFE   ; $8d
	const DRAINING_KISS   ; $8e
	const AQUA_CHARGE   ; $8f
	const RECOLLECT    ; $90
	const WATER_PULSE  ; $91
	const DIZZY_PUNCH  ; $92
	const SPORE        ; $93
	const FLASH        ; $94
	const EXTRASENSORY ; $95
	const CHEER       ; $96
	const TAILWIND ; $97
	const QUAKE_ROAR   ; $98
	const EXPLOSION    ; $99
	const FURY_STRIKES ; $9a
	const SAND_BOMB   ; $9b
	const REST         ; $9c
	const ROCK_SLIDE   ; $9d
	const POWER_BITE   ; $9e
	const BULK_UP      ; $9f
	const CONVERSION   ; $a0
	const FIVEELEMENTS   ; $a1
	const HEAT_CLAW   ; $a2
	const SLASH        ; $a3
	const SUBSTITUTE   ; $a4
	const ULTICHARGE  ; $a5
	const SKETCH       ; $a6
	const DRAIN_PUNCH  ; $a7
	const THIEF        ; $a8
	const WILL_O_WISP  ; $a9
	const BLAZE_STAR ; $aa
	const FACADE       ; $ab
	const FLAME_CHARGE ; $ac
	const VOICE_BIND  ; $ad
	const CURSE        ; $ae
	const GYRO_BALL    ; $af
	const ENERGY_BALL  ; $b0
	const AEROBLAST    ; $b1
	const SEED_BOMB    ; $b2
	const REVERSAL     ; $b3
	const ASTONISH     ; $b4
	const ICE_SHARD    ; $b5
	const PROTECT      ; $b6
	const MACH_PUNCH   ; $b7
	const SCARY_FACE   ; $b8
	const FEINT_ATTACK ; $b9
	const SWEET_KISS   ; $ba
	const BELLY_DRUM   ; $bb
	const SLUDGE_BOMB  ; $bc
	const POISON_GAS     ; $bd
	const BLACK_RIPPLE    ; $be
	const SPIKES       ; $bf
	const ZAP_CANNON   ; $c0
	const FORESIGHT    ; $c1
	const DESTINY_BOND ; $c2
	const SHADOW_DANCE  ; $c3
	const ICY_WIND     ; $c4
	const POWER_GEM    ; $c5
	const WILD_CHARGE  ; $c6
	const POWER_WHIP   ; $c7
	const TOXIC_SPIKES      ; $c8
	const SANDSTORM    ; $c9
	const GIGA_DRAIN   ; $ca
	const ENDURE       ; $cb
	const CHARM        ; $cc
	const TREMORS      ; $cd
	const BLADE_FLASH  ; $ce
	const SWAGGER      ; $cf
	const POWER_TRICK  ; $d0
	const SPARK        ; $d1
	const BULLET_SEED     ; $d2
	const STEEL_WING   ; $d3
	const MEAN_LOOK    ; $d4
	const LUSTER_HEART      ; $d5
	const SLEEP_TALK   ; $d6
	const HEAL_BELL    ; $d7
	const RETURN       ; $d8
	const PSYSTRIKE    ; $d9
	const SPIRIT_VOICE     ; $da
	const SAFEGUARD    ; $db
	const LIFE_BALANCE   ; $dc
	const SACRED_FIRE  ; $dd
	const MAGNITUDE    ; $de
	const DYNAMICPUNCH ; $df
	const DRAIN_DRILL     ; $e0
	const PSYCHO_CUT ; $e1
	const BATON_PASS   ; $e2
	const ENCORE       ; $e3
	const PURSUIT      ; $e4
	const RAPID_SPIN   ; $e5
	const SHADOW_HIT  ; $e6
	const BRAVER    ; $e7
	const METAL_CLAW   ; $e8
	const AURA_SPHERE  ; $e9
	const HEALINGLIGHT ; $ea
	const HURRICANE    ; $eb
	const KNOCK_OFF    ; $ec
	const HIDDEN_POWER ; $ed
	const CROSS_CHOP   ; $ee
	const AQUA_JET     ; $ef
	const RAIN_DANCE   ; $f0
	const SUNNY_DAY    ; $f1
	const GLUTTONY_BITE       ; $f2
	const MIRROR_COAT  ; $f3
	const NASTY_PLOT   ; $f4
	const EXTREMESPEED ; $f5
	const ANCIENTPOWER ; $f6
	const SHADOW_BALL  ; $f7
	const FUTURE_SIGHT ; $f8
	const ROCK_SMASH   ; $f9
if !DEF(FAITHFUL)
DEF BRICK_BREAK EQU ROCK_SMASH
endc
	const WHIRLPOOL     ; $fa
	const DARK_PULSE    ; $fb
	const MOONBLAST     ; $fc
	const PLAY_ROUGH    ; $fd
	const DISARM_VOICE  ; $fe
	const STRUGGLE      ; $ff
DEF NUM_ATTACKS EQU const_value - 1
; Battle animations use the same constants as the moves up to this point
	; These animations don't play if battle anims are disabled.
	const_next $100
	; Pseudo-moves (replaces default move anim for certain species)
	const ANIM_FURY_ATTACK        ; $100
	const ANIM_MILK_DRINK         ; $101
	const ANIM_WITHDRAW           ; $102
	const ANIM_HARDEN             ; $103

	const ANIM_SLP                ; $104
	const ANIM_BRN                ; $105
	const ANIM_PSN                ; $106
	const ANIM_SAP                ; $107
	const ANIM_FRZ                ; $108
	const ANIM_PAR                ; $109
	const ANIM_IN_LOVE            ; $10a
	const ANIM_IN_SANDSTORM       ; $10b
	const ANIM_IN_HAIL            ; $10c
	const ANIM_UNDER_CURSE        ; $10d
	const ANIM_CONFUSED           ; $10e
	const ANIM_STAT_UP            ; $10f
	const ANIM_STAT_DOWN          ; $110
	const ANIM_SHARPEN            ; $111

	; These animations play no matter the battle animation settings
	const ANIM_THROW_TOHO_BALL    ; $112
	const ANIM_SEND_OUT_MON       ; $113
	const ANIM_RETURN_MON         ; $114
	const ANIM_GHOST_TRANSFORM    ; $115

	; Generic "hit" animations
	const ANIM_MISS               ; $116
	const ANIM_ENEMY_DAMAGE       ; $117
	const ANIM_PLAYER_DAMAGE      ; $118
	const ANIM_HIT_PSYSHOT     ; $119
	const ANIM_HELD_ITEM_TRIGGER  ; $11a

DEF ANIM_AFFECTION EQU ANIM_IN_LOVE ; just an alias for now
DEF NUM_BATTLE_ANIMS EQU const_value - 1
DEF FIRST_UNCONDITIONAL_ANIM EQU ANIM_THROW_TOHO_BALL

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_HIT_PSYSHOT
