PicAnimations:
CReimuAnimation:  INCLUDE "gfx/tohomon/creimu/anim.asm"
ReimuAnimation:    INCLUDE "gfx/tohomon/reimu/anim.asm"
TReimuAnimation:   INCLUDE "gfx/tohomon/treimu/anim.asm"
CMarisaAnimation: INCLUDE "gfx/tohomon/cmarisa/anim.asm"
MarisaAnimation: INCLUDE "gfx/tohomon/marisa/anim.asm"
AMarisaAnimation:  INCLUDE "gfx/tohomon/amarisa/anim.asm"
CSakuyaAnimation:   INCLUDE "gfx/tohomon/csakuya/anim.asm"
SakuyaAnimation:  INCLUDE "gfx/tohomon/sakuya/anim.asm"
HSakuyaAnimation:  INCLUDE "gfx/tohomon/hsakuya/anim.asm"
CGyokuAnimation:   INCLUDE "gfx/tohomon/cgyoku/anim.asm"
MGyokuAnimation:    INCLUDE "gfx/tohomon/mgyoku/anim.asm"
FGyokuAnimation: INCLUDE "gfx/tohomon/fgyoku/anim.asm"
OGyokuAnimation:     INCLUDE "gfx/tohomon/ogyoku/anim.asm"
CMaganAnimation:     INCLUDE "gfx/tohomon/cmagan/anim.asm"
MaganAnimation:   INCLUDE "gfx/tohomon/magan/anim.asm"
CMimaAnimation:  INCLUDE "gfx/tohomon/cmima/anim.asm"
MimaAnimation:    INCLUDE "gfx/tohomon/mima/anim.asm"
ElisAnimation:    INCLUDE "gfx/tohomon/elis/anim.asm"
CKikuriAnimation:      INCLUDE "gfx/tohomon/ckikuri/anim.asm"
CKongaraAnimation:   INCLUDE "gfx/tohomon/ckongara/anim.asm"
KongaraAnimation:   INCLUDE "gfx/tohomon/kongara/anim.asm"
CRikaAnimation:   INCLUDE "gfx/tohomon/crika/anim.asm"
RikaAnimation:   INCLUDE "gfx/tohomon/rika/anim.asm"
ARikaAnimation:   INCLUDE "gfx/tohomon/arika/anim.asm"
CMeiraAnimation:   INCLUDE "gfx/tohomon/cmeira/anim.asm"
MeiraAnimation:   INCLUDE "gfx/tohomon/meira/anim.asm"
EllenAnimation: INCLUDE "gfx/tohomon/ellen/anim.asm"
CKotohimeAnimation:      INCLUDE "gfx/tohomon/ckotohime/anim.asm"
KotohimeAnimation:     INCLUDE "gfx/tohomon/kotohime/anim.asm"
CKanaAnimation:      INCLUDE "gfx/tohomon/ckana/anim.asm"
KanaAnimation:  INCLUDE "gfx/tohomon/kana/anim.asm"
CRikakoAnimation:   INCLUDE "gfx/tohomon/crikako/anim.asm"
RikakoAnimation:    INCLUDE "gfx/tohomon/rikako/anim.asm"
YumemiAnimation:    INCLUDE "gfx/tohomon/yumemi/anim.asm"
COrangeAnimation:     INCLUDE "gfx/tohomon/corange/anim.asm"
OrangeAnimation:   INCLUDE "gfx/tohomon/orange/anim.asm"
KurumiAnimation:    INCLUDE "gfx/tohomon/kurumi/anim.asm"
CEllyAnimation:  INCLUDE "gfx/tohomon/celly/anim.asm"
EllyAnimation:       INCLUDE "gfx/tohomon/elly/anim.asm"
CYukaAnimation:   INCLUDE "gfx/tohomon/cyuka/anim.asm"
YukaAnimation:     INCLUDE "gfx/tohomon/yuka/anim.asm"
AYukaAnimation:    INCLUDE "gfx/tohomon/ayuka/anim.asm"
CMugetsuAnimation:    INCLUDE "gfx/tohomon/cmugetsu/anim.asm"
MugetsuAnimation: INCLUDE "gfx/tohomon/mugetsu/anim.asm"
CGengetsuAnimation: INCLUDE "gfx/tohomon/cgengetsu/anim.asm"
GengetsuAnimation:  INCLUDE "gfx/tohomon/gengetsu/anim.asm"
AliceAnimation:  INCLUDE "gfx/tohomon/alice/anim.asm"
AAliceAnimation:   INCLUDE "gfx/tohomon/aalice/anim.asm"
MaiAnimation:      INCLUDE "gfx/tohomon/mai/anim.asm"
CYukiAnimation:       INCLUDE "gfx/tohomon/cyuki/anim.asm"
YukiAnimation:    INCLUDE "gfx/tohomon/yuki/anim.asm"
YumekoAnimation:   INCLUDE "gfx/tohomon/yumeko/anim.asm"
CShinkiAnimation:     INCLUDE "gfx/tohomon/cshinki/anim.asm"
ShinkiAnimation:    INCLUDE "gfx/tohomon/shinki/anim.asm"
CRumiaAnimation:       INCLUDE "gfx/tohomon/crumia/anim.asm"
RumiaAnimation:    INCLUDE "gfx/tohomon/rumia/anim.asm"
ARumiaAnimation:      INCLUDE "gfx/tohomon/arumia/anim.asm"
CDaichanAnimation:     INCLUDE "gfx/tohomon/cdaichan/anim.asm"
DaichanAnimation:    INCLUDE "gfx/tohomon/daichan/anim.asm"
CirnoAnimation:  INCLUDE "gfx/tohomon/cirno/anim.asm"
CMeilingAnimation:     INCLUDE "gfx/tohomon/cmeiling/anim.asm"
AMeilingAnimation:  INCLUDE "gfx/tohomon/ameiling/anim.asm"
CKoakumaAnimation: INCLUDE "gfx/tohomon/ckoakuma/anim.asm"
KoakumaAnimation:  INCLUDE "gfx/tohomon/koakuma/anim.asm"
HKoakumaAnimation:    INCLUDE "gfx/tohomon/hkoakuma/anim.asm"
PatchouliAnimation:    INCLUDE "gfx/tohomon/patchouli/anim.asm"
TPatchouliAnimation:     INCLUDE "gfx/tohomon/tpatchouli/anim.asm"
CRemiliaAnimation:    INCLUDE "gfx/tohomon/cremilia/anim.asm"
RemiliaAnimation:    INCLUDE "gfx/tohomon/remilia/anim.asm"
SRemiliaAnimation: INCLUDE "gfx/tohomon/sremilia/anim.asm"
CFlandreAnimation:     INCLUDE "gfx/tohomon/cflandre/anim.asm"
FlandreAnimation:     INCLUDE "gfx/tohomon/flandre/anim.asm"
AFlandreAnimation:    INCLUDE "gfx/tohomon/aflandre/anim.asm"
CLettyAnimation:    INCLUDE "gfx/tohomon/cletty/anim.asm"
LettyAnimation:     INCLUDE "gfx/tohomon/letty/anim.asm"
DLettyAnimation:    INCLUDE "gfx/tohomon/dletty/anim.asm"
ChenAnimation:    INCLUDE "gfx/tohomon/chen/anim.asm"
HChenAnimation:       INCLUDE "gfx/tohomon/hchen/anim.asm"
CLilyWhiteAnimation: INCLUDE "gfx/tohomon/clilywhite/anim.asm"
LilyWhiteAnimation:     INCLUDE "gfx/tohomon/lilywhite/anim.asm"
DLilyWhiteAnimation:     INCLUDE "gfx/tohomon/dlilywhite/anim.asm"
CLyricaAnimation:     INCLUDE "gfx/tohomon/clyrica/anim.asm"
LyricaAnimation:      INCLUDE "gfx/tohomon/lyrica/anim.asm"
TLyricaAnimation:      INCLUDE "gfx/tohomon/tlyrica/anim.asm"
CMerlinAnimation:   INCLUDE "gfx/tohomon/cmerlin/anim.asm"
MerlinAnimation:    INCLUDE "gfx/tohomon/merlin/anim.asm"
SMerlinAnimation:    INCLUDE "gfx/tohomon/smerlin/anim.asm"
CLunasaAnimation:    INCLUDE "gfx/tohomon/clunasa/anim.asm"
LunasaAnimation:    INCLUDE "gfx/tohomon/lunasa/anim.asm"
ALunasaAnimation:    INCLUDE "gfx/tohomon/alunasa/anim.asm"
CYuyukoAnimation:     INCLUDE "gfx/tohomon/cyuyuko/anim.asm"
YuyukoAnimation:   INCLUDE "gfx/tohomon/yuyuko/anim.asm"
AYuyukoAnimation: INCLUDE "gfx/tohomon/ayuyuko/anim.asm"
CRanAnimation:    INCLUDE "gfx/tohomon/cran/anim.asm"
YukariAnimation:    INCLUDE "gfx/tohomon/yukari/anim.asm"
TYukariAnimation:  INCLUDE "gfx/tohomon/tyukari/anim.asm"
CSuikaAnimation:  INCLUDE "gfx/tohomon/csuika/anim.asm"
TSuikaAnimation:        INCLUDE "gfx/tohomon/tsuika/anim.asm"
CYoumuAnimation:  INCLUDE "gfx/tohomon/cyoumu/anim.asm"
YoumuAnimation:    INCLUDE "gfx/tohomon/youmu/anim.asm"
SYoumuAnimation:   INCLUDE "gfx/tohomon/syoumu/anim.asm"
CReisenAnimation:  INCLUDE "gfx/tohomon/creisen/anim.asm"
ReisenAnimation:    INCLUDE "gfx/tohomon/reisen/anim.asm"
CSanaeAnimation:   INCLUDE "gfx/tohomon/csanae/anim.asm"
SanaeAnimation:   INCLUDE "gfx/tohomon/sanae/anim.asm"
DSanaeAnimation: INCLUDE "gfx/tohomon/dsanae/anim.asm"
CWriggleAnimation:    INCLUDE "gfx/tohomon/cwriggle/anim.asm"
WriggleAnimation:     INCLUDE "gfx/tohomon/wriggle/anim.asm"
SWriggleAnimation:   INCLUDE "gfx/tohomon/swriggle/anim.asm"
CMystiaAnimation:    INCLUDE "gfx/tohomon/cmystia/anim.asm"
MystiaAnimation:     INCLUDE "gfx/tohomon/mystia/anim.asm"
TMystiaAnimation:     INCLUDE "gfx/tohomon/tmystia/anim.asm"
CKeineAnimation:   INCLUDE "gfx/tohomon/ckeine/anim.asm"
KeineAnimation:    INCLUDE "gfx/tohomon/keine/anim.asm"
AKeineAnimation:     INCLUDE "gfx/tohomon/akeine/anim.asm"
CTeiAnimation:   INCLUDE "gfx/tohomon/ctei/anim.asm"
TeiAnimation:    INCLUDE "gfx/tohomon/tei/anim.asm"
CEirinAnimation:     INCLUDE "gfx/tohomon/ceirin/anim.asm"
EirinAnimation:  INCLUDE "gfx/tohomon/eirin/anim.asm"
TEirinAnimation:     INCLUDE "gfx/tohomon/teirin/anim.asm"
CKaguyaAnimation:    INCLUDE "gfx/tohomon/ckaguya/anim.asm"
KaguyaAnimation:       INCLUDE "gfx/tohomon/kaguya/anim.asm"
TKaguyaAnimation:       INCLUDE "gfx/tohomon/tkaguya/anim.asm"
CMokouAnimation:     INCLUDE "gfx/tohomon/cmokou/anim.asm"
MokouAnimation:    INCLUDE "gfx/tohomon/mokou/anim.asm"
AMokouAnimation:   INCLUDE "gfx/tohomon/amokou/anim.asm"
CAyaAnimation:  INCLUDE "gfx/tohomon/caya/anim.asm"
CMedicineAnimation:  INCLUDE "gfx/tohomon/cmedicine/anim.asm"
AyaAnimation:     INCLUDE "gfx/tohomon/aya/anim.asm"
SAyaAnimation:  INCLUDE "gfx/tohomon/saya/anim.asm"
MedicineAnimation:   INCLUDE "gfx/tohomon/medicine/anim.asm"
AMedicineAnimation:     INCLUDE "gfx/tohomon/amedicine/anim.asm"
CKomachiAnimation:   INCLUDE "gfx/tohomon/ckomachi/anim.asm"
KomachiAnimation:   INCLUDE "gfx/tohomon/komachi/anim.asm"
AKomachiAnimation:      INCLUDE "gfx/tohomon/akomachi/anim.asm"
CEikiAnimation:    INCLUDE "gfx/tohomon/ceiki/anim.asm"
EikiAnimation:   INCLUDE "gfx/tohomon/eiki/anim.asm"
AEikiAnimation:      INCLUDE "gfx/tohomon/aeiki/anim.asm"
ShizuhaAnimation:   INCLUDE "gfx/tohomon/shizuha/anim.asm"
SShizuhaAnimation:     INCLUDE "gfx/tohomon/sshizuha/anim.asm"
CMinorikoAnimation:    INCLUDE "gfx/tohomon/cminoriko/anim.asm"
MinorikoAnimation:    INCLUDE "gfx/tohomon/minoriko/anim.asm"
CHinaAnimation: INCLUDE "gfx/tohomon/china/anim.asm"
AHinaAnimation:  INCLUDE "gfx/tohomon/ahina/anim.asm"
CNitoriAnimation:  INCLUDE "gfx/tohomon/cnitori/anim.asm"
NitoriAnimation:     INCLUDE "gfx/tohomon/nitori/anim.asm"
ANitoriAnimation: INCLUDE "gfx/tohomon/anitori/anim.asm"
CMomijiAnimation:  INCLUDE "gfx/tohomon/cmomiji/anim.asm"
MomijiAnimation:     INCLUDE "gfx/tohomon/momiji/anim.asm"
CKanakoAnimation:    INCLUDE "gfx/tohomon/ckanako/anim.asm"
KanakoAnimation:   INCLUDE "gfx/tohomon/kanako/anim.asm"
AKanakoAnimation:   INCLUDE "gfx/tohomon/akanako/anim.asm"
SuwakoAnimation:     INCLUDE "gfx/tohomon/suwako/anim.asm"
DSuwakoAnimation:    INCLUDE "gfx/tohomon/dsuwako/anim.asm"
CIkuAnimation:  INCLUDE "gfx/tohomon/ciku/anim.asm"
AIkuAnimation:  INCLUDE "gfx/tohomon/aiku/anim.asm"
CTenshiAnimation:   INCLUDE "gfx/tohomon/ctenshi/anim.asm"
TenshiAnimation:     INCLUDE "gfx/tohomon/tenshi/anim.asm"
STenshiAnimation:   INCLUDE "gfx/tohomon/stenshi/anim.asm"
CKisumeAnimation:     INCLUDE "gfx/tohomon/ckisume/anim.asm"
KisumeAnimation:  INCLUDE "gfx/tohomon/kisume/anim.asm"
CYamameAnimation:   INCLUDE "gfx/tohomon/cyamame/anim.asm"
YamameAnimation:  INCLUDE "gfx/tohomon/yamame/anim.asm"
SYamameAnimation:   INCLUDE "gfx/tohomon/syamame/anim.asm"
CParseeAnimation:    INCLUDE "gfx/tohomon/cparsee/anim.asm"
ParseeAnimation:   INCLUDE "gfx/tohomon/parsee/anim.asm"
DParseeAnimation:   INCLUDE "gfx/tohomon/dparsee/anim.asm"
CYuugiAnimation:   INCLUDE "gfx/tohomon/cyuugi/anim.asm"
YuugiAnimation:    INCLUDE "gfx/tohomon/yuugi/anim.asm"
AYuugiAnimation:     INCLUDE "gfx/tohomon/ayuugi/anim.asm"
CSatoriAnimation:    INCLUDE "gfx/tohomon/csatori/anim.asm"
SatoriAnimation:   INCLUDE "gfx/tohomon/satori/anim.asm"
HSatoriAnimation:   INCLUDE "gfx/tohomon/hsatori/anim.asm"
CRinAnimation:   INCLUDE "gfx/tohomon/crin/anim.asm"
RinAnimation:    INCLUDE "gfx/tohomon/rin/anim.asm"
HRinAnimation:  INCLUDE "gfx/tohomon/hrin/anim.asm"
CUtsuhoAnimation:   INCLUDE "gfx/tohomon/cutsuho/anim.asm"
UtsuhoAnimation:     INCLUDE "gfx/tohomon/utsuho/anim.asm"
AUtsuhoAnimation:      INCLUDE "gfx/tohomon/autsuho/anim.asm"
CKoishiAnimation:    INCLUDE "gfx/tohomon/ckoishi/anim.asm"
KoishiAnimation:    INCLUDE "gfx/tohomon/koishi/anim.asm"
SKoishiAnimation:     INCLUDE "gfx/tohomon/skoishi/anim.asm"
CNazrinAnimation:      INCLUDE "gfx/tohomon/cnazrin/anim.asm"
NazrinAnimation:    INCLUDE "gfx/tohomon/nazrin/anim.asm"
HNazrinAnimation:   INCLUDE "gfx/tohomon/hnazrin/anim.asm"
CKogasaAnimation:    INCLUDE "gfx/tohomon/ckogasa/anim.asm"
KogasaAnimation:  INCLUDE "gfx/tohomon/kogasa/anim.asm"
TKogasaAnimation:      INCLUDE "gfx/tohomon/tkogasa/anim.asm"
CIchirinAnimation:       INCLUDE "gfx/tohomon/cichirin/anim.asm"
IchirinAnimation:     INCLUDE "gfx/tohomon/ichirin/anim.asm"
AIchirinAnimation:    INCLUDE "gfx/tohomon/aichirin/anim.asm"
CMurasaAnimation:     INCLUDE "gfx/tohomon/cmurasa/anim.asm"
MurasaAnimation:    INCLUDE "gfx/tohomon/murasa/anim.asm"
AMurasaAnimation:  INCLUDE "gfx/tohomon/amurasa/anim.asm"
CShouAnimation:  INCLUDE "gfx/tohomon/cshou/anim.asm"
ShouAnimation:     INCLUDE "gfx/tohomon/shou/anim.asm"
AShouAnimation:     INCLUDE "gfx/tohomon/ashou/anim.asm"
CByakurenAnimation:    INCLUDE "gfx/tohomon/cbyakuren/anim.asm"
ByakurenAnimation:   INCLUDE "gfx/tohomon/byakuren/anim.asm"
TByakurenAnimation:    INCLUDE "gfx/tohomon/tbyakuren/anim.asm"
CNueAnimation:    INCLUDE "gfx/tohomon/cnue/anim.asm"
NueAnimation:  INCLUDE "gfx/tohomon/nue/anim.asm"
SNueAnimation: INCLUDE "gfx/tohomon/snue/anim.asm"
CHatateAnimation:  INCLUDE "gfx/tohomon/chatate/anim.asm"
HatateAnimation:  INCLUDE "gfx/tohomon/hatate/anim.asm"
THatateAnimation: INCLUDE "gfx/tohomon/thatate/anim.asm"
CSunnyAnimation:  INCLUDE "gfx/tohomon/csunny/anim.asm"
SunnyAnimation:   INCLUDE "gfx/tohomon/sunny/anim.asm"
ASunnyAnimation:    INCLUDE "gfx/tohomon/asunny/anim.asm"
CStarAnimation:    INCLUDE "gfx/tohomon/cstar/anim.asm"
StarAnimation:    INCLUDE "gfx/tohomon/star/anim.asm"
AMomijiAnimation:    INCLUDE "gfx/tohomon/amomiji/anim.asm"
DStarAnimation:  INCLUDE "gfx/tohomon/dstar/anim.asm"
CLunaAnimation:   INCLUDE "gfx/tohomon/cluna/anim.asm"
LunaAnimation:    INCLUDE "gfx/tohomon/luna/anim.asm"
TLunaAnimation: INCLUDE "gfx/tohomon/tluna/anim.asm"
CKyoukoAnimation:    INCLUDE "gfx/tohomon/cursola/anim.asm"
KyoukoAnimation:  INCLUDE "gfx/tohomon/sirfetch_d/anim.asm"
CYoshikaAnimation:     INCLUDE "gfx/tohomon/mr__rime/anim.asm"
YoshikaAnimation:    INCLUDE "gfx/tohomon/wyrdeer/anim.asm"
CSeigaAnimation:    INCLUDE "gfx/tohomon/kleavor/anim.asm"
CTojikoAnimation:   INCLUDE "gfx/tohomon/sneasler/anim.asm"
TojikoAnimation:   INCLUDE "gfx/tohomon/overqwil/anim.asm"
MikoAnimation:  INCLUDE "gfx/tohomon/farigiraf/anim.asm"
FutoAnimation:   INCLUDE "gfx/tohomon/clodsire/anim.asm"
CMikoAnimation: INCLUDE "gfx/tohomon/annihilape/anim.asm"

EggAnimation:        INCLUDE "gfx/tohomon/egg/anim.asm"

HinaAAnimation: INCLUDE "gfx/tohomon/hina_a/anim.asm"
HinaBAnimation: INCLUDE "gfx/tohomon/hina_b/anim.asm"
HinaCAnimation: INCLUDE "gfx/tohomon/hina_c/anim.asm"
HinaDAnimation: INCLUDE "gfx/tohomon/hina_d/anim.asm"
HinaEAnimation: INCLUDE "gfx/tohomon/hina_e/anim.asm"
HinaFAnimation: INCLUDE "gfx/tohomon/hina_f/anim.asm"
HinaGAnimation: INCLUDE "gfx/tohomon/hina_g/anim.asm"
HinaHAnimation: INCLUDE "gfx/tohomon/hina_h/anim.asm"
HinaIAnimation: INCLUDE "gfx/tohomon/hina_i/anim.asm"
HinaJAnimation: INCLUDE "gfx/tohomon/hina_j/anim.asm"
HinaKAnimation: INCLUDE "gfx/tohomon/hina_k/anim.asm"
HinaLAnimation: INCLUDE "gfx/tohomon/hina_l/anim.asm"
HinaMAnimation: INCLUDE "gfx/tohomon/hina_m/anim.asm"
HinaNAnimation: INCLUDE "gfx/tohomon/hina_n/anim.asm"
HinaOAnimation: INCLUDE "gfx/tohomon/hina_o/anim.asm"
HinaPAnimation: INCLUDE "gfx/tohomon/hina_p/anim.asm"
HinaQAnimation: INCLUDE "gfx/tohomon/hina_q/anim.asm"
HinaRAnimation: INCLUDE "gfx/tohomon/hina_r/anim.asm"
HinaSAnimation: INCLUDE "gfx/tohomon/hina_s/anim.asm"
HinaTAnimation: INCLUDE "gfx/tohomon/hina_t/anim.asm"
HinaUAnimation: INCLUDE "gfx/tohomon/hina_u/anim.asm"
HinaVAnimation: INCLUDE "gfx/tohomon/hina_v/anim.asm"
HinaWAnimation: INCLUDE "gfx/tohomon/hina_w/anim.asm"
HinaXAnimation: INCLUDE "gfx/tohomon/hina_x/anim.asm"
HinaYAnimation: INCLUDE "gfx/tohomon/hina_y/anim.asm"
HinaZAnimation: INCLUDE "gfx/tohomon/hina_z/anim.asm"
HinaExclamationAnimation: INCLUDE "gfx/tohomon/hina_exclamation/anim.asm"
HinaQuestionAnimation:    INCLUDE "gfx/tohomon/hina_question/anim.asm"

TTeiAnimation: INCLUDE "gfx/tohomon/ttei/anim.asm"
TTeiSpikyAnimation: INCLUDE "gfx/tohomon/ttei_spiky/anim.asm"

KikuriPlainAnimation:  INCLUDE "gfx/tohomon/kikuri/anim.asm"
KikuriFlyAnimation:    INCLUDE "gfx/tohomon/kikuri_fly/anim.asm"
KikuriSurfAnimation:   INCLUDE "gfx/tohomon/kikuri_surf/anim.asm"
KikuriPikaAnimation:   INCLUDE "gfx/tohomon/kikuri_pika/anim.asm"
KikuriChuchuAnimation: INCLUDE "gfx/tohomon/kikuri_chuchu/anim.asm"
KikuriSparkAnimation:  INCLUDE "gfx/tohomon/kikuri_spark/anim.asm"

KikuriArianaAnimation:    INCLUDE "gfx/tohomon/kikuri_ariana/anim.asm"
KikuriAgathaAnimation:   INCLUDE "gfx/tohomon/kikuri_agatha/anim.asm"
KikuriKogaAnimation:   INCLUDE "gfx/tohomon/kikuri_koga/anim.asm"
KikuriKantoAnimation: INCLUDE "gfx/tohomon/kikuri_kanto/anim.asm"
KikuriJohtoAnimation: INCLUDE "gfx/tohomon/kikuri_johto/anim.asm"

LilyBlackAnimation:
LilyBlackRaindropAnimation: INCLUDE "gfx/tohomon/lilyblack/anim.asm"

CFutoTwoSegmentAnimation:   INCLUDE "gfx/tohomon/placethm_two_segment/anim.asm"
CFutoThreeSegmentAnimation: INCLUDE "gfx/tohomon/placethm_three_segment/anim.asm"

SLilyBlackAnimation: INCLUDE "gfx/tohomon/slilyblack/anim.asm"
SLilyBlackRedAnimation:   INCLUDE "gfx/tohomon/slilyblack_red/anim.asm"

SuikaAnimation:   INCLUDE "gfx/tohomon/suika/anim.asm"
SuikaArmoredAnimation: INCLUDE "gfx/tohomon/suika_armored/anim.asm"

CElisAnimation:  INCLUDE "gfx/tohomon/celis/anim.asm"

CSarielAnimation:  INCLUDE "gfx/tohomon/csariel/anim.asm"

SarielAnimation:  INCLUDE "gfx/tohomon/sariel/anim.asm"

CEllenAnimation:  INCLUDE "gfx/tohomon/cellen/anim.asm"

CChiyuriAnimation:  INCLUDE "gfx/tohomon/cchiyuri/anim.asm"

ChiyuriAnimation:  INCLUDE "gfx/tohomon/chiyuri/anim.asm"

CYumemiAnimation:  INCLUDE "gfx/tohomon/cyumemi/anim.asm"

CSaraAnimation:  INCLUDE "gfx/tohomon/csara/anim.asm"

SaraAnimation:  INCLUDE "gfx/tohomon/sara/anim.asm"

CYumekoAnimation:  INCLUDE "gfx/tohomon/cyumeko/anim.asm"

SCirnoAnimation:  INCLUDE "gfx/tohomon/scirno/anim.asm"

MeilingAnimation:  INCLUDE "gfx/tohomon/meiling/anim.asm"

CLuizeAnimation:    INCLUDE "gfx/tohomon/cluize/anim.asm"

LuizeAnimation:    INCLUDE "gfx/tohomon/luize/anim.asm"

DLuizeAnimation:    INCLUDE "gfx/tohomon/dluize/anim.asm"

CAliceAnimation:    INCLUDE "gfx/tohomon/calice/anim.asm"

CMaiAnimation:    INCLUDE "gfx/tohomon/cmai/anim.asm"

CPatchouliAnimation:    INCLUDE "gfx/tohomon/cpatchouli/anim.asm"

CChenAnimation:    INCLUDE "gfx/tohomon/cchen/anim.asm"

RanAnimation:    INCLUDE "gfx/tohomon/ran/anim.asm"

TRanAnimation:    INCLUDE "gfx/tohomon/tran/anim.asm"

CYukariAnimation:    INCLUDE "gfx/tohomon/cyukari/anim.asm"

HMinorikoAnimation:    INCLUDE "gfx/tohomon/hminoriko/anim.asm"

DKisumeAnimation:    INCLUDE "gfx/tohomon/dkisume/anim.asm"

CKurumiAnimation:   INCLUDE "gfx/tohomon/ckurumi/anim.asm"

DDaichanAnimation:   INCLUDE "gfx/tohomon/ddaichan/anim.asm"

CCirnoAnimation:   INCLUDE "gfx/tohomon/ccirno/anim.asm"

TReisenAnimation:   INCLUDE "gfx/tohomon/treisen/anim.asm"

CSuwakoAnimation:   INCLUDE "gfx/tohomon/csuwako/anim.asm"

IkuAnimation:   INCLUDE "gfx/tohomon/iku/anim.asm"

CShizuhaAnimation:   INCLUDE "gfx/tohomon/cshizuha/anim.asm"

CLilyBlackAnimation:        INCLUDE "gfx/tohomon/clilyblack/anim.asm"

SeigaAnimation:        INCLUDE "gfx/tohomon/ursaluna_plain/anim.asm"
