AnimationPointers:
	table_width 2
	dw CReimuAnimation
	dw ReimuAnimation
	dw TReimuAnimation
	dw CMarisaAnimation
	dw MarisaAnimation
	dw AMarisaAnimation
	dw CSakuyaAnimation
	dw SakuyaAnimation
	dw HSakuyaAnimation
	dw CGyokuAnimation
	dw MGyokuAnimation
	dw FGyokuAnimation
	dw OGyokuAnimation
	dw CMaganAnimation
	dw MaganAnimation
	dw CMimaAnimation
	dw MimaAnimation
	dw CElisAnimation
	dw ElisAnimation
	dw CKikuriAnimation
	dw KikuriJohtoAnimation
	dw CSarielAnimation
	dw SarielAnimation
	dw CKongaraAnimation
	dw KongaraAnimation
	dw CRikaAnimation
	dw RikaAnimation
	dw ARikaAnimation
	dw CMeiraAnimation
	dw MeiraAnimation
	dw CEllenAnimation
	dw EllenAnimation
	dw CKotohimeAnimation
	dw KotohimeAnimation
	dw CKanaAnimation
	dw KanaAnimation
	dw CRikakoAnimation
	dw RikakoAnimation
	dw CChiyuriAnimation
	dw ChiyuriAnimation
	dw CYumemiAnimation
	dw YumemiAnimation
	dw COrangeAnimation
	dw OrangeAnimation
	dw CKurumiAnimation
	dw KurumiAnimation
	dw CEllyAnimation
	dw EllyAnimation
	dw CYukaAnimation
	dw YukaAnimation
	dw AYukaAnimation
	dw CMugetsuAnimation
	dw MugetsuAnimation
	dw CGengetsuAnimation
	dw GengetsuAnimation
	dw CSaraAnimation
	dw SaraAnimation
	dw CLuizeAnimation
	dw LuizeAnimation
	dw DLuizeAnimation
	dw CAliceAnimation
	dw AliceAnimation
	dw AAliceAnimation
	dw CMaiAnimation
	dw MaiAnimation
	dw CYukiAnimation
	dw YukiAnimation
	dw CYumekoAnimation
	dw YumekoAnimation
	dw CShinkiAnimation
	dw ShinkiAnimation
	dw CRumiaAnimation
	dw RumiaAnimation
	dw ARumiaAnimation
	dw CDaichanAnimation
	dw DaichanAnimation
	dw DDaichanAnimation
	dw CCirnoAnimation
	dw CirnoAnimation
	dw SCirnoAnimation
	dw CMeilingAnimation
	dw MeilingAnimation
	dw AMeilingAnimation
	dw CKoakumaAnimation
	dw KoakumaAnimation
	dw HKoakumaAnimation
	dw CPatchouliAnimation
	dw PatchouliAnimation
	dw TPatchouliAnimation
	dw CRemiliaAnimation
	dw RemiliaAnimation
	dw SRemiliaAnimation
	dw CFlandreAnimation
	dw FlandreAnimation
	dw AFlandreAnimation
	dw CLettyAnimation
	dw LettyAnimation
	dw DLettyAnimation
	dw CChenAnimation
	dw ChenAnimation
	dw HChenAnimation
	dw CLilyWhiteAnimation
	dw LilyWhiteAnimation
	dw DLilyWhiteAnimation
	dw CLilyBlackAnimation
	dw LilyBlackAnimation
	dw SLilyBlackAnimation
	dw CLyricaAnimation
	dw LyricaAnimation
	dw TLyricaAnimation
	dw CMerlinAnimation
	dw MerlinAnimation
	dw SMerlinAnimation
	dw CLunasaAnimation
	dw LunasaAnimation
	dw ALunasaAnimation
	dw CYuyukoAnimation
	dw YuyukoAnimation
	dw AYuyukoAnimation
	dw CRanAnimation
	dw RanAnimation
	dw TRanAnimation
	dw CYukariAnimation
	dw YukariAnimation
	dw TYukariAnimation
	dw CSuikaAnimation
	dw SuikaAnimation
	dw TSuikaAnimation
	dw CYoumuAnimation
	dw YoumuAnimation
	dw SYoumuAnimation
	dw CReisenAnimation
	dw ReisenAnimation
	dw TReisenAnimation
	dw CSanaeAnimation
	dw SanaeAnimation
	dw DSanaeAnimation
	dw CWriggleAnimation
	dw WriggleAnimation
	dw SWriggleAnimation
	dw CMystiaAnimation
	dw MystiaAnimation
	dw TMystiaAnimation
	dw CKeineAnimation
	dw KeineAnimation
	dw AKeineAnimation
	dw CTeiAnimation
	dw TeiAnimation
	dw TTeiAnimation
	dw CEirinAnimation
	dw EirinAnimation
	dw TEirinAnimation
	dw CKaguyaAnimation
	dw KaguyaAnimation
	dw TKaguyaAnimation
	dw CMokouAnimation
	dw MokouAnimation
	dw AMokouAnimation
	dw CAyaAnimation
	dw AyaAnimation
	dw SAyaAnimation
	dw CMedicineAnimation
	dw MedicineAnimation
	dw AMedicineAnimation
	dw CKomachiAnimation
	dw KomachiAnimation
	dw AKomachiAnimation
	dw CEikiAnimation
	dw EikiAnimation
	dw AEikiAnimation
	dw CShizuhaAnimation
	dw ShizuhaAnimation
	dw SShizuhaAnimation
	dw CMinorikoAnimation
	dw MinorikoAnimation
	dw HMinorikoAnimation
	dw CHinaAnimation
	dw CNueAAnimation
	dw AHinaAnimation
	dw CNitoriAnimation
	dw NitoriAnimation
	dw ANitoriAnimation
	dw CMomijiAnimation
	dw MomijiAnimation
	dw AMomijiAnimation
	dw CKanakoAnimation
	dw KanakoAnimation
	dw AKanakoAnimation
	dw CSuwakoAnimation
	dw SuwakoAnimation
	dw DSuwakoAnimation
	dw CIkuAnimation
	dw IkuAnimation
	dw AIkuAnimation
	dw CTenshiAnimation
	dw TenshiAnimation
	dw STenshiAnimation
	dw CKisumeAnimation
	dw KisumeAnimation
	dw DKisumeAnimation
	dw CYamameAnimation
	dw YamameAnimation
	dw SYamameAnimation
	dw CParseeAnimation
	dw ParseeAnimation
	dw DParseeAnimation
	dw CYuugiAnimation
	dw YuugiAnimation
	dw AYuugiAnimation
	dw EggAnimation
	dw EggAnimation
	dw CSatoriAnimation
	dw SatoriAnimation
	dw HSatoriAnimation
	dw CRinAnimation
	dw RinAnimation
	dw HRinAnimation
	dw CUtsuhoAnimation
	dw UtsuhoAnimation
	dw AUtsuhoAnimation
	dw CKoishiAnimation
	dw KoishiAnimation
	dw SKoishiAnimation
	dw CNazrinAnimation
	dw NazrinAnimation
	dw HNazrinAnimation
	dw CKogasaAnimation
	dw KogasaAnimation
	dw TKogasaAnimation
	dw CIchirinAnimation
	dw IchirinAnimation
	dw AIchirinAnimation
	dw CMurasaAnimation
	dw MurasaAnimation
	dw AMurasaAnimation
	dw CShouAnimation
	dw ShouAnimation
	dw AShouAnimation
	dw CByakurenAnimation
	dw ByakurenAnimation
	dw TByakurenAnimation
	dw HinaAnimation
	dw NueAnimation
	dw SNueAnimation
	dw CHatateAnimation
	dw HatateAnimation
	dw THatateAnimation
	dw CSunnyAnimation
	dw SunnyAnimation
	dw ASunnyAnimation
	dw CStarAnimation
	dw StarAnimation
	dw DStarAnimation
	dw CLunaAnimation
	dw LunaAnimation
	dw TLunaAnimation
	dw CKyoukoAnimation
	dw KyoukoAnimation
	dw CYoshikaAnimation
	dw YoshikaAnimation
	dw CSeigaAnimation
	dw SeigaAnimation
	dw CTojikoAnimation
	dw TojikoAnimation
	dw CFutoTwoSegmentAnimation
	dw MikoAnimation
	dw FutoAnimation
	dw CMikoAnimation
	dw CMamizouAnimation
	dw MamizouAnimation
	dw CKokoroAnimation
	dw KokoroAnimation
	dw CWakasagiAnimation
	dw WakasagiAnimation
	dw CSekibakiAnimation
	dw SekibakiAnimation
	dw CKagerouAnimation
	dw KagerouAnimation
	dw CBenbenAnimation
	dw BenbenAnimation
	dw CYatsuhaAnimation
	dw YatsuhaAnimation
	dw CSeijaAnimation
	dw SeijaAnimation
	dw CSukunaAnimation
	dw SukunaAnimation
	dw CRaikoAnimation
	dw RaikoAnimation
	dw CKasenAnimation
	dw KasenAnimation
	dw CSumirekoAnimation
	dw SumirekoAnimation
	assert_table_length NUM_SPECIES

	dw CNueBAnimation
	dw CNueCAnimation
	dw CNueDAnimation
	dw CNueEAnimation
	dw CNueFAnimation
	dw CNueGAnimation
	dw CNueHAnimation
	dw CNueIAnimation
	dw CNueJAnimation
	dw CNueKAnimation
	dw CNueLAnimation
	dw CNueMAnimation
	dw CNueNAnimation
	dw CNueOAnimation
	dw CNuePAnimation
	dw CNueQAnimation
	dw CNueRAnimation
	dw CNueSAnimation
	dw CNueTAnimation
	dw CNueUAnimation
	dw CNueVAnimation
	dw CNueWAnimation
	dw CNueXAnimation
	dw CNueYAnimation
	dw CNueZAnimation
	dw CNueExclamationAnimation
	dw CNueQuestionAnimation

	dw KikuriKantoAnimation
	dw KikuriKogaAnimation
	dw KikuriAgathaAnimation
	dw KikuriArianaAnimation

	dw TTeiSpikyAnimation

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedAnimation

	dw SuikaArmoredAnimation

	dw CFutoThreeSegmentAnimation

	assert_table_length NUM_UNIQUE_TOHOMON
