CReimuBitmasks:  INCLUDE "gfx/tohomon/creimu/bitmask.asm"
ReimuBitmasks:    INCLUDE "gfx/tohomon/reimu/bitmask.asm"
TReimuBitmasks:   INCLUDE "gfx/tohomon/treimu/bitmask.asm"
CMarisaBitmasks: INCLUDE "gfx/tohomon/cmarisa/bitmask.asm"
MarisaBitmasks: INCLUDE "gfx/tohomon/marisa/bitmask.asm"
AMarisaBitmasks:  INCLUDE "gfx/tohomon/amarisa/bitmask.asm"
CSakuyaBitmasks:   INCLUDE "gfx/tohomon/csakuya/bitmask.asm"
SakuyaBitmasks:  INCLUDE "gfx/tohomon/sakuya/bitmask.asm"
HSakuyaBitmasks:  INCLUDE "gfx/tohomon/hsakuya/bitmask.asm"
CGyokuBitmasks:   INCLUDE "gfx/tohomon/cgyoku/bitmask.asm"
MGyokuBitmasks:    INCLUDE "gfx/tohomon/mgyoku/bitmask.asm"
FGyokuBitmasks: INCLUDE "gfx/tohomon/fgyoku/bitmask.asm"
OGyokuBitmasks:     INCLUDE "gfx/tohomon/ogyoku/bitmask.asm"
CMaganBitmasks:     INCLUDE "gfx/tohomon/cmagan/bitmask.asm"
MaganBitmasks:   INCLUDE "gfx/tohomon/magan/bitmask.asm"
CMimaBitmasks:  INCLUDE "gfx/tohomon/cmima/bitmask.asm"
MimaBitmasks:    INCLUDE "gfx/tohomon/mima/bitmask.asm"
ElisBitmasks:    INCLUDE "gfx/tohomon/elis/bitmask.asm"
CKikuriBitmasks:      INCLUDE "gfx/tohomon/ckikuri/bitmask.asm"
CKongaraBitmasks:   INCLUDE "gfx/tohomon/ckongara/bitmask.asm"
KongaraBitmasks:   INCLUDE "gfx/tohomon/kongara/bitmask.asm"
CRikaBitmasks:   INCLUDE "gfx/tohomon/crika/bitmask.asm"
RikaBitmasks:   INCLUDE "gfx/tohomon/rika/bitmask.asm"
ARikaBitmasks:   INCLUDE "gfx/tohomon/arika/bitmask.asm"
CMeiraBitmasks:   INCLUDE "gfx/tohomon/cmeira/bitmask.asm"
MeiraBitmasks:   INCLUDE "gfx/tohomon/meira/bitmask.asm"
EllenBitmasks: INCLUDE "gfx/tohomon/ellen/bitmask.asm"
CKotohimeBitmasks:      INCLUDE "gfx/tohomon/ckotohime/bitmask.asm"
KotohimeBitmasks:     INCLUDE "gfx/tohomon/kotohime/bitmask.asm"
CKanaBitmasks:      INCLUDE "gfx/tohomon/ckana/bitmask.asm"
KanaBitmasks:  INCLUDE "gfx/tohomon/kana/bitmask.asm"
CRikakoBitmasks:   INCLUDE "gfx/tohomon/crikako/bitmask.asm"
RikakoBitmasks:    INCLUDE "gfx/tohomon/rikako/bitmask.asm"
YumemiBitmasks:    INCLUDE "gfx/tohomon/yumemi/bitmask.asm"
COrangeBitmasks:     INCLUDE "gfx/tohomon/corange/bitmask.asm"
OrangeBitmasks:   INCLUDE "gfx/tohomon/orange/bitmask.asm"
KurumiBitmasks:    INCLUDE "gfx/tohomon/kurumi/bitmask.asm"
CEllyBitmasks:  INCLUDE "gfx/tohomon/celly/bitmask.asm"
EllyBitmasks:       INCLUDE "gfx/tohomon/elly/bitmask.asm"
CYukaBitmasks:   INCLUDE "gfx/tohomon/cyuka/bitmask.asm"
YukaBitmasks:     INCLUDE "gfx/tohomon/yuka/bitmask.asm"
AYukaBitmasks:    INCLUDE "gfx/tohomon/ayuka/bitmask.asm"
CMugetsuBitmasks:    INCLUDE "gfx/tohomon/cmugetsu/bitmask.asm"
MugetsuBitmasks: INCLUDE "gfx/tohomon/mugetsu/bitmask.asm"
CGengetsuBitmasks: INCLUDE "gfx/tohomon/cgengetsu/bitmask.asm"
GengetsuBitmasks:  INCLUDE "gfx/tohomon/gengetsu/bitmask.asm"
AliceBitmasks:  INCLUDE "gfx/tohomon/alice/bitmask.asm"
AAliceBitmasks:   INCLUDE "gfx/tohomon/aalice/bitmask.asm"
MaiBitmasks:      INCLUDE "gfx/tohomon/mai/bitmask.asm"
CYukiBitmasks:       INCLUDE "gfx/tohomon/cyuki/bitmask.asm"
YukiBitmasks:    INCLUDE "gfx/tohomon/yuki/bitmask.asm"
YumekoBitmasks:   INCLUDE "gfx/tohomon/yumeko/bitmask.asm"
CShinkiBitmasks:     INCLUDE "gfx/tohomon/cshinki/bitmask.asm"
ShinkiBitmasks:    INCLUDE "gfx/tohomon/shinki/bitmask.asm"
CRumiaBitmasks:       INCLUDE "gfx/tohomon/crumia/bitmask.asm"
RumiaBitmasks:    INCLUDE "gfx/tohomon/rumia/bitmask.asm"
ARumiaBitmasks:      INCLUDE "gfx/tohomon/arumia/bitmask.asm"
CDaichanBitmasks:     INCLUDE "gfx/tohomon/cdaichan/bitmask.asm"
DaichanBitmasks:    INCLUDE "gfx/tohomon/daichan/bitmask.asm"
CirnoBitmasks:  INCLUDE "gfx/tohomon/cirno/bitmask.asm"
CMeilingBitmasks:     INCLUDE "gfx/tohomon/cmeiling/bitmask.asm"
AMeilingBitmasks:  INCLUDE "gfx/tohomon/ameiling/bitmask.asm"
CKoakumaBitmasks: INCLUDE "gfx/tohomon/ckoakuma/bitmask.asm"
KoakumaBitmasks:  INCLUDE "gfx/tohomon/koakuma/bitmask.asm"
HKoakumaBitmasks:    INCLUDE "gfx/tohomon/hkoakuma/bitmask.asm"
PatchouliBitmasks:    INCLUDE "gfx/tohomon/patchouli/bitmask.asm"
TPatchouliBitmasks:     INCLUDE "gfx/tohomon/tpatchouli/bitmask.asm"
CRemiliaBitmasks:    INCLUDE "gfx/tohomon/cremilia/bitmask.asm"
RemiliaBitmasks:    INCLUDE "gfx/tohomon/remilia/bitmask.asm"
SRemiliaBitmasks: INCLUDE "gfx/tohomon/sremilia/bitmask.asm"
CFlandreBitmasks:     INCLUDE "gfx/tohomon/cflandre/bitmask.asm"
FlandreBitmasks:     INCLUDE "gfx/tohomon/flandre/bitmask.asm"
AFlandreBitmasks:    INCLUDE "gfx/tohomon/aflandre/bitmask.asm"
CLettyBitmasks:    INCLUDE "gfx/tohomon/cletty/bitmask.asm"
LettyBitmasks:     INCLUDE "gfx/tohomon/letty/bitmask.asm"
DLettyBitmasks:    INCLUDE "gfx/tohomon/dletty/bitmask.asm"
ChenBitmasks:    INCLUDE "gfx/tohomon/chen/bitmask.asm"
HChenBitmasks:       INCLUDE "gfx/tohomon/hchen/bitmask.asm"
CLilyWhiteBitmasks: INCLUDE "gfx/tohomon/clilywhite/bitmask.asm"
LilyWhiteBitmasks:     INCLUDE "gfx/tohomon/lilywhite/bitmask.asm"
DLilyWhiteBitmasks:     INCLUDE "gfx/tohomon/dlilywhite/bitmask.asm"
CLyricaBitmasks:     INCLUDE "gfx/tohomon/clyrica/bitmask.asm"
LyricaBitmasks:      INCLUDE "gfx/tohomon/lyrica/bitmask.asm"
TLyricaBitmasks:      INCLUDE "gfx/tohomon/tlyrica/bitmask.asm"
CMerlinBitmasks:   INCLUDE "gfx/tohomon/cmerlin/bitmask.asm"
MerlinBitmasks:    INCLUDE "gfx/tohomon/merlin/bitmask.asm"
SMerlinBitmasks:    INCLUDE "gfx/tohomon/smerlin/bitmask.asm"
CLunasaBitmasks:    INCLUDE "gfx/tohomon/clunasa/bitmask.asm"
LunasaBitmasks:    INCLUDE "gfx/tohomon/lunasa/bitmask.asm"
ALunasaBitmasks:    INCLUDE "gfx/tohomon/alunasa/bitmask.asm"
CYuyukoBitmasks:     INCLUDE "gfx/tohomon/cyuyuko/bitmask.asm"
YuyukoBitmasks:   INCLUDE "gfx/tohomon/yuyuko/bitmask.asm"
AYuyukoBitmasks: INCLUDE "gfx/tohomon/ayuyuko/bitmask.asm"
CRanBitmasks:    INCLUDE "gfx/tohomon/cran/bitmask.asm"
YukariBitmasks:    INCLUDE "gfx/tohomon/yukari/bitmask.asm"
TYukariBitmasks:  INCLUDE "gfx/tohomon/tyukari/bitmask.asm"
CSuikaBitmasks:  INCLUDE "gfx/tohomon/csuika/bitmask.asm"
TSuikaBitmasks:        INCLUDE "gfx/tohomon/tsuika/bitmask.asm"
CYoumuBitmasks:  INCLUDE "gfx/tohomon/cyoumu/bitmask.asm"
YoumuBitmasks:    INCLUDE "gfx/tohomon/youmu/bitmask.asm"
SYoumuBitmasks:   INCLUDE "gfx/tohomon/syoumu/bitmask.asm"
CReisenBitmasks:  INCLUDE "gfx/tohomon/creisen/bitmask.asm"
ReisenBitmasks:    INCLUDE "gfx/tohomon/reisen/bitmask.asm"
CSanaeBitmasks:   INCLUDE "gfx/tohomon/csanae/bitmask.asm"
SanaeBitmasks:   INCLUDE "gfx/tohomon/sanae/bitmask.asm"
DSanaeBitmasks: INCLUDE "gfx/tohomon/dsanae/bitmask.asm"
CWriggleBitmasks:    INCLUDE "gfx/tohomon/cwriggle/bitmask.asm"
WriggleBitmasks:     INCLUDE "gfx/tohomon/wriggle/bitmask.asm"
SWriggleBitmasks:   INCLUDE "gfx/tohomon/swriggle/bitmask.asm"
CMystiaBitmasks:    INCLUDE "gfx/tohomon/cmystia/bitmask.asm"
MystiaBitmasks:     INCLUDE "gfx/tohomon/mystia/bitmask.asm"
TMystiaBitmasks:     INCLUDE "gfx/tohomon/tmystia/bitmask.asm"
CKeineBitmasks:   INCLUDE "gfx/tohomon/ckeine/bitmask.asm"
KeineBitmasks:    INCLUDE "gfx/tohomon/keine/bitmask.asm"
AKeineBitmasks:     INCLUDE "gfx/tohomon/akeine/bitmask.asm"
CTeiBitmasks:   INCLUDE "gfx/tohomon/ctei/bitmask.asm"
TeiBitmasks:    INCLUDE "gfx/tohomon/tei/bitmask.asm"
CEirinBitmasks:     INCLUDE "gfx/tohomon/ceirin/bitmask.asm"
EirinBitmasks:  INCLUDE "gfx/tohomon/eirin/bitmask.asm"
TEirinBitmasks:     INCLUDE "gfx/tohomon/teirin/bitmask.asm"
CKaguyaBitmasks:    INCLUDE "gfx/tohomon/ckaguya/bitmask.asm"
KaguyaBitmasks:       INCLUDE "gfx/tohomon/kaguya/bitmask.asm"
TKaguyaBitmasks:       INCLUDE "gfx/tohomon/tkaguya/bitmask.asm"
CMokouBitmasks:     INCLUDE "gfx/tohomon/cmokou/bitmask.asm"
MokouBitmasks:    INCLUDE "gfx/tohomon/mokou/bitmask.asm"
AMokouBitmasks:   INCLUDE "gfx/tohomon/amokou/bitmask.asm"
CAyaBitmasks:  INCLUDE "gfx/tohomon/caya/bitmask.asm"
CMedicineBitmasks:  INCLUDE "gfx/tohomon/cmedicine/bitmask.asm"
AyaBitmasks:     INCLUDE "gfx/tohomon/aya/bitmask.asm"
SAyaBitmasks:  INCLUDE "gfx/tohomon/saya/bitmask.asm"
MedicineBitmasks:   INCLUDE "gfx/tohomon/medicine/bitmask.asm"
AMedicineBitmasks:     INCLUDE "gfx/tohomon/amedicine/bitmask.asm"
CKomachiBitmasks:   INCLUDE "gfx/tohomon/ckomachi/bitmask.asm"
KomachiBitmasks:   INCLUDE "gfx/tohomon/komachi/bitmask.asm"
AKomachiBitmasks:      INCLUDE "gfx/tohomon/akomachi/bitmask.asm"
CEikiBitmasks:    INCLUDE "gfx/tohomon/ceiki/bitmask.asm"
EikiBitmasks:   INCLUDE "gfx/tohomon/eiki/bitmask.asm"
AEikiBitmasks:      INCLUDE "gfx/tohomon/aeiki/bitmask.asm"
ShizuhaBitmasks:   INCLUDE "gfx/tohomon/shizuha/bitmask.asm"
SShizuhaBitmasks:     INCLUDE "gfx/tohomon/sshizuha/bitmask.asm"
CMinorikoBitmasks:    INCLUDE "gfx/tohomon/cminoriko/bitmask.asm"
MinorikoBitmasks:    INCLUDE "gfx/tohomon/minoriko/bitmask.asm"
CHinaBitmasks: INCLUDE "gfx/tohomon/china/bitmask.asm"
AHinaBitmasks:  INCLUDE "gfx/tohomon/ahina/bitmask.asm"
CNitoriBitmasks:  INCLUDE "gfx/tohomon/cnitori/bitmask.asm"
NitoriBitmasks:     INCLUDE "gfx/tohomon/nitori/bitmask.asm"
ANitoriBitmasks: INCLUDE "gfx/tohomon/anitori/bitmask.asm"
CMomijiBitmasks:  INCLUDE "gfx/tohomon/cmomiji/bitmask.asm"
MomijiBitmasks:     INCLUDE "gfx/tohomon/momiji/bitmask.asm"
CKanakoBitmasks:    INCLUDE "gfx/tohomon/ckanako/bitmask.asm"
KanakoBitmasks:   INCLUDE "gfx/tohomon/kanako/bitmask.asm"
AKanakoBitmasks:   INCLUDE "gfx/tohomon/akanako/bitmask.asm"
SuwakoBitmasks:     INCLUDE "gfx/tohomon/suwako/bitmask.asm"
DSuwakoBitmasks:    INCLUDE "gfx/tohomon/dsuwako/bitmask.asm"
CIkuBitmasks:  INCLUDE "gfx/tohomon/ciku/bitmask.asm"
AIkuBitmasks:  INCLUDE "gfx/tohomon/aiku/bitmask.asm"
CTenshiBitmasks:   INCLUDE "gfx/tohomon/ctenshi/bitmask.asm"
TenshiBitmasks:     INCLUDE "gfx/tohomon/tenshi/bitmask.asm"
STenshiBitmasks:   INCLUDE "gfx/tohomon/stenshi/bitmask.asm"
CKisumeBitmasks:     INCLUDE "gfx/tohomon/ckisume/bitmask.asm"
KisumeBitmasks:  INCLUDE "gfx/tohomon/kisume/bitmask.asm"
CYamameBitmasks:   INCLUDE "gfx/tohomon/cyamame/bitmask.asm"
YamameBitmasks:  INCLUDE "gfx/tohomon/yamame/bitmask.asm"
SYamameBitmasks:   INCLUDE "gfx/tohomon/syamame/bitmask.asm"
CParseeBitmasks:    INCLUDE "gfx/tohomon/cparsee/bitmask.asm"
ParseeBitmasks:   INCLUDE "gfx/tohomon/parsee/bitmask.asm"
DParseeBitmasks:   INCLUDE "gfx/tohomon/dparsee/bitmask.asm"
CYuugiBitmasks:   INCLUDE "gfx/tohomon/cyuugi/bitmask.asm"
YuugiBitmasks:    INCLUDE "gfx/tohomon/yuugi/bitmask.asm"
AYuugiBitmasks:     INCLUDE "gfx/tohomon/ayuugi/bitmask.asm"
CSatoriBitmasks:    INCLUDE "gfx/tohomon/csatori/bitmask.asm"
SatoriBitmasks:   INCLUDE "gfx/tohomon/satori/bitmask.asm"
HSatoriBitmasks:   INCLUDE "gfx/tohomon/hsatori/bitmask.asm"
CRinBitmasks:   INCLUDE "gfx/tohomon/crin/bitmask.asm"
RinBitmasks:    INCLUDE "gfx/tohomon/rin/bitmask.asm"
HRinBitmasks:  INCLUDE "gfx/tohomon/hrin/bitmask.asm"
CUtsuhoBitmasks:   INCLUDE "gfx/tohomon/cutsuho/bitmask.asm"
UtsuhoBitmasks:     INCLUDE "gfx/tohomon/utsuho/bitmask.asm"
AUtsuhoBitmasks:      INCLUDE "gfx/tohomon/autsuho/bitmask.asm"
CKoishiBitmasks:    INCLUDE "gfx/tohomon/ckoishi/bitmask.asm"
KoishiBitmasks:    INCLUDE "gfx/tohomon/koishi/bitmask.asm"
SKoishiBitmasks:     INCLUDE "gfx/tohomon/skoishi/bitmask.asm"
CNazrinBitmasks:      INCLUDE "gfx/tohomon/entei/bitmask.asm"
NazrinBitmasks:    INCLUDE "gfx/tohomon/suicune/bitmask.asm"
HNazrinBitmasks:   INCLUDE "gfx/tohomon/larvitar/bitmask.asm"
CKogasaBitmasks:    INCLUDE "gfx/tohomon/pupitar/bitmask.asm"
KogasaBitmasks:  INCLUDE "gfx/tohomon/tyranitar/bitmask.asm"
TKogasaBitmasks:      INCLUDE "gfx/tohomon/lugia/bitmask.asm"
CIchirinBitmasks:       INCLUDE "gfx/tohomon/ho_oh/bitmask.asm"
IchirinBitmasks:     INCLUDE "gfx/tohomon/celebi/bitmask.asm"
AIchirinBitmasks:    INCLUDE "gfx/tohomon/azurill/bitmask.asm"
CMurasaBitmasks:     INCLUDE "gfx/tohomon/wynaut/bitmask.asm"
MurasaBitmasks:    INCLUDE "gfx/tohomon/ambipom/bitmask.asm"
AMurasaBitmasks:  INCLUDE "gfx/tohomon/mismagius/bitmask.asm"
CShouBitmasks:  INCLUDE "gfx/tohomon/honchkrow/bitmask.asm"
ShouBitmasks:     INCLUDE "gfx/tohomon/bonsly/bitmask.asm"
AShouBitmasks:     INCLUDE "gfx/tohomon/mime_jr_/bitmask.asm"
CByakurenBitmasks:    INCLUDE "gfx/tohomon/happiny/bitmask.asm"
ByakurenBitmasks:   INCLUDE "gfx/tohomon/munchlax/bitmask.asm"
TByakurenBitmasks:    INCLUDE "gfx/tohomon/mantyke/bitmask.asm"
CNueBitmasks:    INCLUDE "gfx/tohomon/weavile/bitmask.asm"
NueBitmasks:  INCLUDE "gfx/tohomon/magnezone/bitmask.asm"
SNueBitmasks: INCLUDE "gfx/tohomon/lickilicky/bitmask.asm"
CHatateBitmasks:  INCLUDE "gfx/tohomon/rhyperior/bitmask.asm"
HatateBitmasks:  INCLUDE "gfx/tohomon/tangrowth/bitmask.asm"
THatateBitmasks: INCLUDE "gfx/tohomon/electivire/bitmask.asm"
CSunnyBitmasks:  INCLUDE "gfx/tohomon/magmortar/bitmask.asm"
SunnyBitmasks:   INCLUDE "gfx/tohomon/togekiss/bitmask.asm"
ASunnyBitmasks:    INCLUDE "gfx/tohomon/yanmega/bitmask.asm"
CStarBitmasks:    INCLUDE "gfx/tohomon/leafeon/bitmask.asm"
StarBitmasks:    INCLUDE "gfx/tohomon/glaceon/bitmask.asm"
AMomijiBitmasks:    INCLUDE "gfx/tohomon/amomiji/bitmask.asm"
DStarBitmasks:  INCLUDE "gfx/tohomon/mamoswine/bitmask.asm"
CLunaBitmasks:   INCLUDE "gfx/tohomon/clunasa_z/bitmask.asm"
LunaBitmasks:    INCLUDE "gfx/tohomon/sylveon/bitmask.asm"
TLunaBitmasks: INCLUDE "gfx/tohomon/perrserker/bitmask.asm"
CKyoukoBitmasks:    INCLUDE "gfx/tohomon/cursola/bitmask.asm"
KyoukoBitmasks:  INCLUDE "gfx/tohomon/sirfetch_d/bitmask.asm"
CYoshikaBitmasks:     INCLUDE "gfx/tohomon/mr__rime/bitmask.asm"
YoshikaBitmasks:    INCLUDE "gfx/tohomon/wyrdeer/bitmask.asm"
CSeigaBitmasks:    INCLUDE "gfx/tohomon/kleavor/bitmask.asm"
CTojikoBitmasks:   INCLUDE "gfx/tohomon/sneasler/bitmask.asm"
TojikoBitmasks:   INCLUDE "gfx/tohomon/overqwil/bitmask.asm"
MikoBitmasks:  INCLUDE "gfx/tohomon/farigiraf/bitmask.asm"
FutoBitmasks:   INCLUDE "gfx/tohomon/clodsire/bitmask.asm"
CMikoBitmasks: INCLUDE "gfx/tohomon/annihilape/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/tohomon/egg/bitmask.asm"

HinaABitmasks: INCLUDE "gfx/tohomon/hina_a/bitmask.asm"
HinaBBitmasks: INCLUDE "gfx/tohomon/hina_b/bitmask.asm"
HinaCBitmasks: INCLUDE "gfx/tohomon/hina_c/bitmask.asm"
HinaDBitmasks: INCLUDE "gfx/tohomon/hina_d/bitmask.asm"
HinaEBitmasks: INCLUDE "gfx/tohomon/hina_e/bitmask.asm"
HinaFBitmasks: INCLUDE "gfx/tohomon/hina_f/bitmask.asm"
HinaGBitmasks: INCLUDE "gfx/tohomon/hina_g/bitmask.asm"
HinaHBitmasks: INCLUDE "gfx/tohomon/hina_h/bitmask.asm"
HinaIBitmasks: INCLUDE "gfx/tohomon/hina_i/bitmask.asm"
HinaJBitmasks: INCLUDE "gfx/tohomon/hina_j/bitmask.asm"
HinaKBitmasks: INCLUDE "gfx/tohomon/hina_k/bitmask.asm"
HinaLBitmasks: INCLUDE "gfx/tohomon/hina_l/bitmask.asm"
HinaMBitmasks: INCLUDE "gfx/tohomon/hina_m/bitmask.asm"
HinaNBitmasks: INCLUDE "gfx/tohomon/hina_n/bitmask.asm"
HinaOBitmasks: INCLUDE "gfx/tohomon/hina_o/bitmask.asm"
HinaPBitmasks: INCLUDE "gfx/tohomon/hina_p/bitmask.asm"
HinaQBitmasks: INCLUDE "gfx/tohomon/hina_q/bitmask.asm"
HinaRBitmasks: INCLUDE "gfx/tohomon/hina_r/bitmask.asm"
HinaSBitmasks: INCLUDE "gfx/tohomon/hina_s/bitmask.asm"
HinaTBitmasks: INCLUDE "gfx/tohomon/hina_t/bitmask.asm"
HinaUBitmasks: INCLUDE "gfx/tohomon/hina_u/bitmask.asm"
HinaVBitmasks: INCLUDE "gfx/tohomon/hina_v/bitmask.asm"
HinaWBitmasks: INCLUDE "gfx/tohomon/hina_w/bitmask.asm"
HinaXBitmasks: INCLUDE "gfx/tohomon/hina_x/bitmask.asm"
HinaYBitmasks: INCLUDE "gfx/tohomon/hina_y/bitmask.asm"
HinaZBitmasks: INCLUDE "gfx/tohomon/hina_z/bitmask.asm"
HinaExclamationBitmasks: INCLUDE "gfx/tohomon/hina_exclamation/bitmask.asm"
HinaQuestionBitmasks:    INCLUDE "gfx/tohomon/hina_question/bitmask.asm"

TTeiBitmasks: INCLUDE "gfx/tohomon/ttei/bitmask.asm"
TTeiSpikyBitmasks: INCLUDE "gfx/tohomon/ttei_spiky/bitmask.asm"

KikuriPlainBitmasks:  INCLUDE "gfx/tohomon/kikuri/bitmask.asm"
KikuriFlyBitmasks:    INCLUDE "gfx/tohomon/kikuri_fly/bitmask.asm"
KikuriSurfBitmasks:   INCLUDE "gfx/tohomon/kikuri_surf/bitmask.asm"
KikuriPikaBitmasks:   INCLUDE "gfx/tohomon/kikuri_pika/bitmask.asm"
KikuriChuchuBitmasks: INCLUDE "gfx/tohomon/kikuri_chuchu/bitmask.asm"
KikuriSparkBitmasks:  INCLUDE "gfx/tohomon/kikuri_spark/bitmask.asm"
KikuriArianaBitmasks:   INCLUDE "gfx/tohomon/kikuri_ariana/bitmask.asm"
KikuriAgathaBitmasks:   INCLUDE "gfx/tohomon/kikuri_agatha/bitmask.asm"
KikuriKogaBitmasks: INCLUDE "gfx/tohomon/kikuri_koga/bitmask.asm"
KikuriKantoBitmasks:  INCLUDE "gfx/tohomon/kikuri_kanto/bitmask.asm"
KikuriJohtoBitmasks:  INCLUDE "gfx/tohomon/kikuri_johto/bitmask.asm"

LilyBlackBitmasks:     INCLUDE "gfx/tohomon/lilyblack/bitmask.asm"

CFutoTwoSegmentBitmasks:   INCLUDE "gfx/tohomon/placethm_two_segment/bitmask.asm"
CFutoThreeSegmentBitmasks: INCLUDE "gfx/tohomon/placethm_three_segment/bitmask.asm"

SLilyBlackBitmasks: INCLUDE "gfx/tohomon/slilyblack/bitmask.asm"
SLilyBlackRedBitmasks:   INCLUDE "gfx/tohomon/slilyblack_red/bitmask.asm"

SuikaBitmasks:   INCLUDE "gfx/tohomon/suika/bitmask.asm"
SuikaArmoredBitmasks: INCLUDE "gfx/tohomon/suika_armored/bitmask.asm"

CElisBitmasks:  INCLUDE "gfx/tohomon/celis/bitmask.asm"

CSarielBitmasks:  INCLUDE "gfx/tohomon/csariel/bitmask.asm"

SarielBitmasks:  INCLUDE "gfx/tohomon/sariel/bitmask.asm"

CEllenBitmasks:  INCLUDE "gfx/tohomon/cellen/bitmask.asm"

CChiyuriBitmasks:  INCLUDE "gfx/tohomon/cchiyuri/bitmask.asm"

ChiyuriBitmasks:  INCLUDE "gfx/tohomon/chiyuri/bitmask.asm"

CYumemiBitmasks:  INCLUDE "gfx/tohomon/cyumemi/bitmask.asm"

CSaraBitmasks:  INCLUDE "gfx/tohomon/csara/bitmask.asm"

SaraBitmasks:  INCLUDE "gfx/tohomon/sara/bitmask.asm"


CYumekoBitmasks:  INCLUDE "gfx/tohomon/cyumeko/bitmask.asm"

SCirnoBitmasks:  INCLUDE "gfx/tohomon/scirno/bitmask.asm"

MeilingBitmasks:  INCLUDE "gfx/tohomon/meiling/bitmask.asm"

CLuizeBitmasks:    INCLUDE "gfx/tohomon/cluize/bitmask.asm"

LuizeBitmasks:    INCLUDE "gfx/tohomon/luize/bitmask.asm"

DLuizeBitmasks:   INCLUDE "gfx/tohomon/dluize/bitmask.asm"

CAliceBitmasks:    INCLUDE "gfx/tohomon/calice/bitmask.asm"

CMaiBitmasks:     INCLUDE "gfx/tohomon/cmai/bitmask.asm"

CPatchouliBitmasks:    INCLUDE "gfx/tohomon/cpatchouli/bitmask.asm"

CChenBitmasks:    INCLUDE "gfx/tohomon/cchen/bitmask.asm"

RanBitmasks:    INCLUDE "gfx/tohomon/ran/bitmask.asm"

TRanBitmasks:    INCLUDE "gfx/tohomon/tran/bitmask.asm"

CYukariBitmasks:    INCLUDE "gfx/tohomon/cyukari/bitmask.asm"

HMinorikoBitmasks:    INCLUDE "gfx/tohomon/hminoriko/bitmask.asm"

DKisumeBitmasks:    INCLUDE "gfx/tohomon/dkisume/bitmask.asm"

CKurumiBitmasks:   INCLUDE "gfx/tohomon/ckurumi/bitmask.asm"

DDaichanBitmasks:   INCLUDE "gfx/tohomon/ddaichan/bitmask.asm"

CCirnoBitmasks:   INCLUDE "gfx/tohomon/ccirno/bitmask.asm"

TReisenBitmasks:   INCLUDE "gfx/tohomon/treisen/bitmask.asm"

CSuwakoBitmasks:   INCLUDE "gfx/tohomon/csuwako/bitmask.asm"

IkuBitmasks:   INCLUDE "gfx/tohomon/iku/bitmask.asm"

CShizuhaBitmasks:    INCLUDE "gfx/tohomon/cshizuha/bitmask.asm"
CLilyBlackBitmasks:        INCLUDE "gfx/tohomon/clilyblack/bitmask.asm"

SeigaBitmasks:        INCLUDE "gfx/tohomon/ursaluna_plain/bitmask.asm"
