BitmasksPointers:
	table_width 2
	dw CReimuBitmasks
	dw ReimuBitmasks
	dw TReimuBitmasks
	dw CMarisaBitmasks
	dw MarisaBitmasks
	dw AMarisaBitmasks
	dw CSakuyaBitmasks
	dw SakuyaBitmasks
	dw HSakuyaBitmasks
	dw CGyokuBitmasks
	dw MGyokuBitmasks
	dw FGyokuBitmasks
	dw OGyokuBitmasks
	dw CMaganBitmasks
	dw MaganBitmasks
	dw CMimaBitmasks
	dw MimaBitmasks
	dw CElisBitmasks
	dw ElisBitmasks
	dw CKikuriBitmasks
	dw KikuriJohtoBitmasks
	dw CSarielBitmasks
	dw SarielBitmasks
	dw CKongaraBitmasks
	dw KongaraBitmasks
	dw CRikaBitmasks
	dw RikaBitmasks
	dw ARikaBitmasks
	dw CMeiraBitmasks
	dw MeiraBitmasks
	dw CEllenBitmasks
	dw EllenBitmasks
	dw CKotohimeBitmasks
	dw KotohimeBitmasks
	dw CKanaBitmasks
	dw KanaBitmasks
	dw CRikakoBitmasks
	dw RikakoBitmasks
	dw CChiyuriBitmasks
	dw ChiyuriBitmasks
	dw CYumemiBitmasks
	dw YumemiBitmasks
	dw COrangeBitmasks
	dw OrangeBitmasks
	dw CKurumiBitmasks
	dw KurumiBitmasks
	dw CEllyBitmasks
	dw EllyBitmasks
	dw CYukaBitmasks
	dw YukaBitmasks
	dw AYukaBitmasks
	dw CMugetsuBitmasks
	dw MugetsuBitmasks
	dw CGengetsuBitmasks
	dw GengetsuBitmasks
	dw CSaraBitmasks
	dw SaraBitmasks
	dw CLuizeBitmasks
	dw LuizeBitmasks
	dw DLuizeBitmasks
	dw CAliceBitmasks
	dw AliceBitmasks
	dw AAliceBitmasks
	dw CMaiBitmasks
	dw MaiBitmasks
	dw CYukiBitmasks
	dw YukiBitmasks
	dw CYumekoBitmasks
	dw YumekoBitmasks
	dw CShinkiBitmasks
	dw ShinkiBitmasks
	dw CRumiaBitmasks
	dw RumiaBitmasks
	dw ARumiaBitmasks
	dw CDaichanBitmasks
	dw DaichanBitmasks
	dw DDaichanBitmasks
	dw CCirnoBitmasks
	dw CirnoBitmasks
	dw SCirnoBitmasks
	dw CMeilingBitmasks
	dw MeilingBitmasks
	dw AMeilingBitmasks
	dw CKoakumaBitmasks
	dw KoakumaBitmasks
	dw HKoakumaBitmasks
	dw CPatchouliBitmasks
	dw PatchouliBitmasks
	dw TPatchouliBitmasks
	dw CRemiliaBitmasks
	dw RemiliaBitmasks
	dw SRemiliaBitmasks
	dw CFlandreBitmasks
	dw FlandreBitmasks
	dw AFlandreBitmasks
	dw CLettyBitmasks
	dw LettyBitmasks
	dw DLettyBitmasks
	dw CChenBitmasks
	dw ChenBitmasks
	dw HChenBitmasks
	dw CLilyWhiteBitmasks
	dw LilyWhiteBitmasks
	dw DLilyWhiteBitmasks
	dw CLilyBlackBitmasks
	dw LilyBlackBitmasks
	dw SLilyBlackBitmasks
	dw CLyricaBitmasks
	dw LyricaBitmasks
	dw TLyricaBitmasks
	dw CMerlinBitmasks
	dw MerlinBitmasks
	dw SMerlinBitmasks
	dw CLunasaBitmasks
	dw LunasaBitmasks
	dw ALunasaBitmasks
	dw CYuyukoBitmasks
	dw YuyukoBitmasks
	dw AYuyukoBitmasks
	dw CRanBitmasks
	dw RanBitmasks
	dw TRanBitmasks
	dw CYukariBitmasks
	dw YukariBitmasks
	dw TYukariBitmasks
	dw CSuikaBitmasks
	dw SuikaBitmasks
	dw TSuikaBitmasks
	dw CYoumuBitmasks
	dw YoumuBitmasks
	dw SYoumuBitmasks
	dw CReisenBitmasks
	dw ReisenBitmasks
	dw TReisenBitmasks
	dw CSanaeBitmasks
	dw SanaeBitmasks
	dw DSanaeBitmasks
	dw CWriggleBitmasks
	dw WriggleBitmasks
	dw SWriggleBitmasks
	dw CMystiaBitmasks
	dw MystiaBitmasks
	dw TMystiaBitmasks
	dw CKeineBitmasks
	dw KeineBitmasks
	dw AKeineBitmasks
	dw CTeiBitmasks
	dw TeiBitmasks
	dw TTeiBitmasks
	dw CEirinBitmasks
	dw EirinBitmasks
	dw TEirinBitmasks
	dw CKaguyaBitmasks
	dw KaguyaBitmasks
	dw TKaguyaBitmasks
	dw CMokouBitmasks
	dw MokouBitmasks
	dw AMokouBitmasks
	dw CAyaBitmasks
	dw AyaBitmasks
	dw SAyaBitmasks
	dw CMedicineBitmasks
	dw MedicineBitmasks
	dw AMedicineBitmasks
	dw CKomachiBitmasks
	dw KomachiBitmasks
	dw AKomachiBitmasks
	dw CEikiBitmasks
	dw EikiBitmasks
	dw AEikiBitmasks
	dw CShizuhaBitmasks
	dw ShizuhaBitmasks
	dw SShizuhaBitmasks
	dw CMinorikoBitmasks
	dw MinorikoBitmasks
	dw HMinorikoBitmasks
	dw CHinaBitmasks
	dw CNueABitmasks
	dw AHinaBitmasks
	dw CNitoriBitmasks
	dw NitoriBitmasks
	dw ANitoriBitmasks
	dw CMomijiBitmasks
	dw MomijiBitmasks
	dw AMomijiBitmasks
	dw CKanakoBitmasks
	dw KanakoBitmasks
	dw AKanakoBitmasks
	dw CSuwakoBitmasks
	dw SuwakoBitmasks
	dw DSuwakoBitmasks
	dw CIkuBitmasks
	dw IkuBitmasks
	dw AIkuBitmasks
	dw CTenshiBitmasks
	dw TenshiBitmasks
	dw STenshiBitmasks
	dw CKisumeBitmasks
	dw KisumeBitmasks
	dw DKisumeBitmasks
	dw CYamameBitmasks
	dw YamameBitmasks
	dw SYamameBitmasks
	dw CParseeBitmasks
	dw ParseeBitmasks
	dw DParseeBitmasks
	dw CYuugiBitmasks
	dw YuugiBitmasks
	dw AYuugiBitmasks
	dw CSatoriBitmasks
	dw SatoriBitmasks
	dw HSatoriBitmasks
	dw CRinBitmasks
	dw RinBitmasks
	dw HRinBitmasks
	dw CUtsuhoBitmasks
	dw UtsuhoBitmasks
	dw AUtsuhoBitmasks
	dw CKoishiBitmasks
	dw KoishiBitmasks
	dw SKoishiBitmasks
	dw CNazrinBitmasks
	dw NazrinBitmasks
	dw HNazrinBitmasks
	dw CKogasaBitmasks
	dw KogasaBitmasks
	dw TKogasaBitmasks
	dw CIchirinBitmasks
	dw IchirinBitmasks
	dw AIchirinBitmasks
	dw CMurasaBitmasks
	dw MurasaBitmasks
	dw AMurasaBitmasks
	dw CShouBitmasks
	dw ShouBitmasks
	dw AShouBitmasks
	dw CByakurenBitmasks
	dw ByakurenBitmasks
	dw TByakurenBitmasks
	dw HinaBitmasks
	dw NueBitmasks
	dw SNueBitmasks
	dw CHatateBitmasks
	dw HatateBitmasks
	dw THatateBitmasks
	dw CSunnyBitmasks
	dw SunnyBitmasks
	dw ASunnyBitmasks
	dw CStarBitmasks
	dw StarBitmasks
	dw DStarBitmasks
	dw CLunaBitmasks
	dw LunaBitmasks
	dw TLunaBitmasks
	dw CKyoukoBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw KyoukoBitmasks
	dw CYoshikaBitmasks
	dw YoshikaBitmasks
	dw CSeigaBitmasks
	dw SeigaBitmasks
	dw CTojikoBitmasks
	dw TojikoBitmasks
	dw CFutoTwoSegmentBitmasks
	dw MikoBitmasks
	dw FutoBitmasks
	dw CMikoBitmasks
	dw CMamizouBitmasks
	dw MamizouBitmasks
	dw CKokoroBitmasks
	dw KokoroBitmasks
	dw CWakasagiBitmasks
	dw WakasagiBitmasks
	dw CSekibakiBitmasks
	dw SekibakiBitmasks
	dw CKagerouBitmasks
	dw KagerouBitmasks
	dw CBenbenBitmasks
	dw BenbenBitmasks
	dw CYatsuhaBitmasks
	dw YatsuhaBitmasks
	dw CSeijaBitmasks
	dw SeijaBitmasks
	dw CSukunaBitmasks
	dw SukunaBitmasks
	dw CRaikoBitmasks
	dw RaikoBitmasks
	dw CKasenBitmasks
	dw KasenBitmasks
	dw CSumirekoBitmasks
	dw SumirekoBitmasks
	assert_table_length NUM_SPECIES

	dw CNueBBitmasks
	dw CNueCBitmasks
	dw CNueDBitmasks
	dw CNueEBitmasks
	dw CNueFBitmasks
	dw CNueGBitmasks
	dw CNueHBitmasks
	dw CNueIBitmasks
	dw CNueJBitmasks
	dw CNueKBitmasks
	dw CNueLBitmasks
	dw CNueMBitmasks
	dw CNueNBitmasks
	dw CNueOBitmasks
	dw CNuePBitmasks
	dw CNueQBitmasks
	dw CNueRBitmasks
	dw CNueSBitmasks
	dw CNueTBitmasks
	dw CNueUBitmasks
	dw CNueVBitmasks
	dw CNueWBitmasks
	dw CNueXBitmasks
	dw CNueYBitmasks
	dw CNueZBitmasks
	dw CNueExclamationBitmasks
	dw CNueQuestionBitmasks

	dw KikuriKantoBitmasks
	dw KikuriKogaBitmasks
	dw KikuriAgathaBitmasks
	dw KikuriArianaBitmasks

	dw TTeiSpikyBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedBitmasks

	dw SuikaArmoredBitmasks

	dw CFutoThreeSegmentBitmasks

	assert_table_length NUM_UNIQUE_TOHOMON
