CReimuAnimationExtra:  INCLUDE "gfx/tohomon/creimu/anim_idle.asm"
ReimuAnimationExtra:    INCLUDE "gfx/tohomon/reimu/anim_idle.asm"
TReimuAnimationExtra:   INCLUDE "gfx/tohomon/treimu/anim_idle.asm"
CMarisaAnimationExtra: INCLUDE "gfx/tohomon/cmarisa/anim_idle.asm"
MarisaAnimationExtra: INCLUDE "gfx/tohomon/marisa/anim_idle.asm"
AMarisaAnimationExtra:  INCLUDE "gfx/tohomon/amarisa/anim_idle.asm"
CSakuyaAnimationExtra:   INCLUDE "gfx/tohomon/csakuya/anim_idle.asm"
SakuyaAnimationExtra:  INCLUDE "gfx/tohomon/sakuya/anim_idle.asm"
HSakuyaAnimationExtra:  INCLUDE "gfx/tohomon/hsakuya/anim_idle.asm"
CGyokuAnimationExtra:   INCLUDE "gfx/tohomon/cgyoku/anim_idle.asm"
MGyokuAnimationExtra:    INCLUDE "gfx/tohomon/mgyoku/anim_idle.asm"
FGyokuAnimationExtra: INCLUDE "gfx/tohomon/fgyoku/anim_idle.asm"
OGyokuAnimationExtra:     INCLUDE "gfx/tohomon/ogyoku/anim_idle.asm"
CMaganAnimationExtra:     INCLUDE "gfx/tohomon/cmagan/anim_idle.asm"
MaganAnimationExtra:   INCLUDE "gfx/tohomon/magan/anim_idle.asm"
CMimaAnimationExtra:  INCLUDE "gfx/tohomon/cmima/anim_idle.asm"
MimaAnimationExtra:    INCLUDE "gfx/tohomon/mima/anim_idle.asm"
ElisAnimationExtra:    INCLUDE "gfx/tohomon/elis/anim_idle.asm"
CKikuriAnimationExtra:      INCLUDE "gfx/tohomon/ckikuri/anim_idle.asm"
CKongaraAnimationExtra:   INCLUDE "gfx/tohomon/ckongara/anim_idle.asm"
KongaraAnimationExtra:   INCLUDE "gfx/tohomon/kongara/anim_idle.asm"
CRikaAnimationExtra:   INCLUDE "gfx/tohomon/crika/anim_idle.asm"
RikaAnimationExtra:   INCLUDE "gfx/tohomon/rika/anim_idle.asm"
ARikaAnimationExtra:   INCLUDE "gfx/tohomon/arika/anim_idle.asm"
CMeiraAnimationExtra:   INCLUDE "gfx/tohomon/cmeira/anim_idle.asm"
MeiraAnimationExtra:   INCLUDE "gfx/tohomon/meira/anim_idle.asm"
EllenAnimationExtra: INCLUDE "gfx/tohomon/ellen/anim_idle.asm"
CKotohimeAnimationExtra:      INCLUDE "gfx/tohomon/ckotohime/anim_idle.asm"
KotohimeAnimationExtra:     INCLUDE "gfx/tohomon/kotohime/anim_idle.asm"
CKanaAnimationExtra:      INCLUDE "gfx/tohomon/ckana/anim_idle.asm"
KanaAnimationExtra:  INCLUDE "gfx/tohomon/kana/anim_idle.asm"
CRikakoAnimationExtra:   INCLUDE "gfx/tohomon/crikako/anim_idle.asm"
RikakoAnimationExtra:    INCLUDE "gfx/tohomon/rikako/anim_idle.asm"
YumemiAnimationExtra:    INCLUDE "gfx/tohomon/yumemi/anim_idle.asm"
COrangeAnimationExtra:     INCLUDE "gfx/tohomon/corange/anim_idle.asm"
OrangeAnimationExtra:   INCLUDE "gfx/tohomon/orange/anim_idle.asm"
KurumiAnimationExtra:    INCLUDE "gfx/tohomon/kurumi/anim_idle.asm"
CEllyAnimationExtra:  INCLUDE "gfx/tohomon/celly/anim_idle.asm"
EllyAnimationExtra:       INCLUDE "gfx/tohomon/elly/anim_idle.asm"
CYukaAnimationExtra:   INCLUDE "gfx/tohomon/cyuka/anim_idle.asm"
YukaAnimationExtra:     INCLUDE "gfx/tohomon/yuka/anim_idle.asm"
AYukaAnimationExtra:    INCLUDE "gfx/tohomon/ayuka/anim_idle.asm"
CMugetsuAnimationExtra:    INCLUDE "gfx/tohomon/cmugetsu/anim_idle.asm"
MugetsuAnimationExtra: INCLUDE "gfx/tohomon/mugetsu/anim_idle.asm"
CGengetsuAnimationExtra: INCLUDE "gfx/tohomon/cgengetsu/anim_idle.asm"
GengetsuAnimationExtra:  INCLUDE "gfx/tohomon/gengetsu/anim_idle.asm"
AliceAnimationExtra:  INCLUDE "gfx/tohomon/alice/anim_idle.asm"
AAliceAnimationExtra:   INCLUDE "gfx/tohomon/aalice/anim_idle.asm"
MaiAnimationExtra:      INCLUDE "gfx/tohomon/mai/anim_idle.asm"
CYukiAnimationExtra:       INCLUDE "gfx/tohomon/cyuki/anim_idle.asm"
YukiAnimationExtra:    INCLUDE "gfx/tohomon/yuki/anim_idle.asm"
YumekoAnimationExtra:   INCLUDE "gfx/tohomon/yumeko/anim_idle.asm"
CShinkiAnimationExtra:     INCLUDE "gfx/tohomon/cshinki/anim_idle.asm"
ShinkiAnimationExtra:    INCLUDE "gfx/tohomon/shinki/anim_idle.asm"
CRumiaAnimationExtra:       INCLUDE "gfx/tohomon/crumia/anim_idle.asm"
RumiaAnimationExtra:    INCLUDE "gfx/tohomon/rumia/anim_idle.asm"
ARumiaAnimationExtra:      INCLUDE "gfx/tohomon/arumia/anim_idle.asm"
CDaichanAnimationExtra:     INCLUDE "gfx/tohomon/cdaichan/anim_idle.asm"
DaichanAnimationExtra:    INCLUDE "gfx/tohomon/daichan/anim_idle.asm"
CirnoAnimationExtra:  INCLUDE "gfx/tohomon/cirno/anim_idle.asm"
CMeilingAnimationExtra:     INCLUDE "gfx/tohomon/cmeiling/anim_idle.asm"
AMeilingAnimationExtra:  INCLUDE "gfx/tohomon/ameiling/anim_idle.asm"
CKoakumaAnimationExtra: INCLUDE "gfx/tohomon/ckoakuma/anim_idle.asm"
KoakumaAnimationExtra:  INCLUDE "gfx/tohomon/koakuma/anim_idle.asm"
HKoakumaAnimationExtra:    INCLUDE "gfx/tohomon/hkoakuma/anim_idle.asm"
PatchouliAnimationExtra:    INCLUDE "gfx/tohomon/patchouli/anim_idle.asm"
TPatchouliAnimationExtra:     INCLUDE "gfx/tohomon/tpatchouli/anim_idle.asm"
CRemiliaAnimationExtra:    INCLUDE "gfx/tohomon/cremilia/anim_idle.asm"
RemiliaAnimationExtra:    INCLUDE "gfx/tohomon/remilia/anim_idle.asm"
SRemiliaAnimationExtra: INCLUDE "gfx/tohomon/sremilia/anim_idle.asm"
CFlandreAnimationExtra:     INCLUDE "gfx/tohomon/cflandre/anim_idle.asm"
FlandreAnimationExtra:     INCLUDE "gfx/tohomon/flandre/anim_idle.asm"
AFlandreAnimationExtra:    INCLUDE "gfx/tohomon/aflandre/anim_idle.asm"
CLettyAnimationExtra:    INCLUDE "gfx/tohomon/cletty/anim_idle.asm"
LettyAnimationExtra:     INCLUDE "gfx/tohomon/letty/anim_idle.asm"
DLettyAnimationExtra:    INCLUDE "gfx/tohomon/dletty/anim_idle.asm"
ChenAnimationExtra:    INCLUDE "gfx/tohomon/chen/anim_idle.asm"
HChenAnimationExtra:       INCLUDE "gfx/tohomon/hchen/anim_idle.asm"
CLilyWhiteAnimationExtra: INCLUDE "gfx/tohomon/clilywhite/anim_idle.asm"
LilyWhiteAnimationExtra:     INCLUDE "gfx/tohomon/lilywhite/anim_idle.asm"
DLilyWhiteAnimationExtra:     INCLUDE "gfx/tohomon/dlilywhite/anim_idle.asm"
CLyricaAnimationExtra:     INCLUDE "gfx/tohomon/clyrica/anim_idle.asm"
LyricaAnimationExtra:      INCLUDE "gfx/tohomon/lyrica/anim_idle.asm"
TLyricaAnimationExtra:      INCLUDE "gfx/tohomon/tlyrica/anim_idle.asm"
CMerlinAnimationExtra:   INCLUDE "gfx/tohomon/cmerlin/anim_idle.asm"
MerlinAnimationExtra:    INCLUDE "gfx/tohomon/merlin/anim_idle.asm"
SMerlinAnimationExtra:    INCLUDE "gfx/tohomon/smerlin/anim_idle.asm"
CLunasaAnimationExtra:    INCLUDE "gfx/tohomon/clunasa/anim_idle.asm"
LunasaAnimationExtra:    INCLUDE "gfx/tohomon/lunasa/anim_idle.asm"
ALunasaAnimationExtra:    INCLUDE "gfx/tohomon/alunasa/anim_idle.asm"
CYuyukoAnimationExtra:     INCLUDE "gfx/tohomon/cyuyuko/anim_idle.asm"
YuyukoAnimationExtra:   INCLUDE "gfx/tohomon/yuyuko/anim_idle.asm"
AYuyukoAnimationExtra: INCLUDE "gfx/tohomon/ayuyuko/anim_idle.asm"
CRanAnimationExtra:    INCLUDE "gfx/tohomon/cran/anim_idle.asm"
YukariAnimationExtra:    INCLUDE "gfx/tohomon/yukari/anim_idle.asm"
TYukariAnimationExtra:  INCLUDE "gfx/tohomon/tyukari/anim_idle.asm"
CSuikaAnimationExtra:  INCLUDE "gfx/tohomon/csuika/anim_idle.asm"
TSuikaAnimationExtra:        INCLUDE "gfx/tohomon/tsuika/anim_idle.asm"
CYoumuAnimationExtra:  INCLUDE "gfx/tohomon/cyoumu/anim_idle.asm"
YoumuAnimationExtra:    INCLUDE "gfx/tohomon/youmu/anim_idle.asm"
SYoumuAnimationExtra:   INCLUDE "gfx/tohomon/syoumu/anim_idle.asm"
CReisenAnimationExtra:  INCLUDE "gfx/tohomon/creisen/anim_idle.asm"
ReisenAnimationExtra:    INCLUDE "gfx/tohomon/reisen/anim_idle.asm"
CSanaeAnimationExtra:   INCLUDE "gfx/tohomon/csanae/anim_idle.asm"
SanaeAnimationExtra:   INCLUDE "gfx/tohomon/sanae/anim_idle.asm"
DSanaeAnimationExtra: INCLUDE "gfx/tohomon/dsanae/anim_idle.asm"
CWriggleAnimationExtra:    INCLUDE "gfx/tohomon/cwriggle/anim_idle.asm"
WriggleAnimationExtra:     INCLUDE "gfx/tohomon/wriggle/anim_idle.asm"
SWriggleAnimationExtra:   INCLUDE "gfx/tohomon/swriggle/anim_idle.asm"
CMystiaAnimationExtra:    INCLUDE "gfx/tohomon/cmystia/anim_idle.asm"
MystiaAnimationExtra:     INCLUDE "gfx/tohomon/mystia/anim_idle.asm"
TMystiaAnimationExtra:     INCLUDE "gfx/tohomon/tmystia/anim_idle.asm"
CKeineAnimationExtra:   INCLUDE "gfx/tohomon/ckeine/anim_idle.asm"
KeineAnimationExtra:    INCLUDE "gfx/tohomon/keine/anim_idle.asm"
AKeineAnimationExtra:     INCLUDE "gfx/tohomon/akeine/anim_idle.asm"
CTeiAnimationExtra:   INCLUDE "gfx/tohomon/ctei/anim_idle.asm"
TeiAnimationExtra:    INCLUDE "gfx/tohomon/tei/anim_idle.asm"
CEirinAnimationExtra:     INCLUDE "gfx/tohomon/ceirin/anim_idle.asm"
EirinAnimationExtra:  INCLUDE "gfx/tohomon/eirin/anim_idle.asm"
TEirinAnimationExtra:     INCLUDE "gfx/tohomon/teirin/anim_idle.asm"
CKaguyaAnimationExtra:    INCLUDE "gfx/tohomon/ckaguya/anim_idle.asm"
KaguyaAnimationExtra:       INCLUDE "gfx/tohomon/kaguya/anim_idle.asm"
TKaguyaAnimationExtra:       INCLUDE "gfx/tohomon/tkaguya/anim_idle.asm"
CMokouAnimationExtra:     INCLUDE "gfx/tohomon/cmokou/anim_idle.asm"
MokouAnimationExtra:    INCLUDE "gfx/tohomon/mokou/anim_idle.asm"
AMokouAnimationExtra:   INCLUDE "gfx/tohomon/amokou/anim_idle.asm"
CAyaAnimationExtra:  INCLUDE "gfx/tohomon/caya/anim_idle.asm"
CMedicineAnimationExtra:  INCLUDE "gfx/tohomon/cmedicine/anim_idle.asm"
AyaAnimationExtra:     INCLUDE "gfx/tohomon/aya/anim_idle.asm"
SAyaAnimationExtra:  INCLUDE "gfx/tohomon/saya/anim_idle.asm"
MedicineAnimationExtra:   INCLUDE "gfx/tohomon/medicine/anim_idle.asm"
AMedicineAnimationExtra:     INCLUDE "gfx/tohomon/amedicine/anim_idle.asm"
CKomachiAnimationExtra:   INCLUDE "gfx/tohomon/ckomachi/anim_idle.asm"
KomachiAnimationExtra:   INCLUDE "gfx/tohomon/komachi/anim_idle.asm"
AKomachiAnimationExtra:      INCLUDE "gfx/tohomon/akomachi/anim_idle.asm"
CEikiAnimationExtra:    INCLUDE "gfx/tohomon/ceiki/anim_idle.asm"
EikiAnimationExtra:   INCLUDE "gfx/tohomon/eiki/anim_idle.asm"
AEikiAnimationExtra:      INCLUDE "gfx/tohomon/aeiki/anim_idle.asm"
ShizuhaAnimationExtra:   INCLUDE "gfx/tohomon/shizuha/anim_idle.asm"
SShizuhaAnimationExtra:     INCLUDE "gfx/tohomon/sshizuha/anim_idle.asm"
CMinorikoAnimationExtra:    INCLUDE "gfx/tohomon/cminoriko/anim_idle.asm"
MinorikoAnimationExtra:    INCLUDE "gfx/tohomon/minoriko/anim_idle.asm"
CHinaAnimationExtra: INCLUDE "gfx/tohomon/china/anim_idle.asm"
AHinaAnimationExtra:  INCLUDE "gfx/tohomon/ahina/anim_idle.asm"
CNitoriAnimationExtra:  INCLUDE "gfx/tohomon/cnitori/anim_idle.asm"
NitoriAnimationExtra:     INCLUDE "gfx/tohomon/nitori/anim_idle.asm"
ANitoriAnimationExtra: INCLUDE "gfx/tohomon/anitori/anim_idle.asm"
CMomijiAnimationExtra:  INCLUDE "gfx/tohomon/cmomiji/anim_idle.asm"
MomijiAnimationExtra:     INCLUDE "gfx/tohomon/momiji/anim_idle.asm"
CKanakoAnimationExtra:    INCLUDE "gfx/tohomon/ckanako/anim_idle.asm"
KanakoAnimationExtra:   INCLUDE "gfx/tohomon/kanako/anim_idle.asm"
AKanakoAnimationExtra:   INCLUDE "gfx/tohomon/akanako/anim_idle.asm"
SuwakoAnimationExtra:     INCLUDE "gfx/tohomon/suwako/anim_idle.asm"
DSuwakoAnimationExtra:    INCLUDE "gfx/tohomon/dsuwako/anim_idle.asm"
CIkuAnimationExtra:  INCLUDE "gfx/tohomon/ciku/anim_idle.asm"
AIkuAnimationExtra:  INCLUDE "gfx/tohomon/aiku/anim_idle.asm"
CTenshiAnimationExtra:   INCLUDE "gfx/tohomon/ctenshi/anim_idle.asm"
TenshiAnimationExtra:     INCLUDE "gfx/tohomon/tenshi/anim_idle.asm"
STenshiAnimationExtra:   INCLUDE "gfx/tohomon/stenshi/anim_idle.asm"
CKisumeAnimationExtra:     INCLUDE "gfx/tohomon/ckisume/anim_idle.asm"
KisumeAnimationExtra:  INCLUDE "gfx/tohomon/kisume/anim_idle.asm"
CYamameAnimationExtra:   INCLUDE "gfx/tohomon/cyamame/anim_idle.asm"
YamameAnimationExtra:  INCLUDE "gfx/tohomon/yamame/anim_idle.asm"
SYamameAnimationExtra:   INCLUDE "gfx/tohomon/syamame/anim_idle.asm"
CParseeAnimationExtra:    INCLUDE "gfx/tohomon/cparsee/anim_idle.asm"
ParseeAnimationExtra:   INCLUDE "gfx/tohomon/parsee/anim_idle.asm"
DParseeAnimationExtra:   INCLUDE "gfx/tohomon/dparsee/anim_idle.asm"
CYuugiAnimationExtra:   INCLUDE "gfx/tohomon/cyuugi/anim_idle.asm"
YuugiAnimationExtra:    INCLUDE "gfx/tohomon/yuugi/anim_idle.asm"
AYuugiAnimationExtra:     INCLUDE "gfx/tohomon/ayuugi/anim_idle.asm"
CSatoriAnimationExtra:    INCLUDE "gfx/tohomon/csatori/anim_idle.asm"
SatoriAnimationExtra:   INCLUDE "gfx/tohomon/satori/anim_idle.asm"
HSatoriAnimationExtra:   INCLUDE "gfx/tohomon/hsatori/anim_idle.asm"
CRinAnimationExtra:   INCLUDE "gfx/tohomon/crin/anim_idle.asm"
RinAnimationExtra:    INCLUDE "gfx/tohomon/rin/anim_idle.asm"
HRinAnimationExtra:  INCLUDE "gfx/tohomon/hrin/anim_idle.asm"
CUtsuhoAnimationExtra:   INCLUDE "gfx/tohomon/cutsuho/anim_idle.asm"
UtsuhoAnimationExtra:     INCLUDE "gfx/tohomon/utsuho/anim_idle.asm"
AUtsuhoAnimationExtra:      INCLUDE "gfx/tohomon/autsuho/anim_idle.asm"
CKoishiAnimationExtra:    INCLUDE "gfx/tohomon/ckoishi/anim_idle.asm"
KoishiAnimationExtra:    INCLUDE "gfx/tohomon/koishi/anim_idle.asm"
SKoishiAnimationExtra:     INCLUDE "gfx/tohomon/skoishi/anim_idle.asm"
CNazrinAnimationExtra:      INCLUDE "gfx/tohomon/entei/anim_idle.asm"
NazrinAnimationExtra:    INCLUDE "gfx/tohomon/suicune/anim_idle.asm"
HNazrinAnimationExtra:   INCLUDE "gfx/tohomon/larvitar/anim_idle.asm"
CKogasaAnimationExtra:    INCLUDE "gfx/tohomon/pupitar/anim_idle.asm"
KogasaAnimationExtra:  INCLUDE "gfx/tohomon/tyranitar/anim_idle.asm"
TKogasaAnimationExtra:      INCLUDE "gfx/tohomon/lugia/anim_idle.asm"
CIchirinAnimationExtra:       INCLUDE "gfx/tohomon/ho_oh/anim_idle.asm"
IchirinAnimationExtra:     INCLUDE "gfx/tohomon/celebi/anim_idle.asm"
AIchirinAnimationExtra:    INCLUDE "gfx/tohomon/azurill/anim_idle.asm"
CMurasaAnimationExtra:     INCLUDE "gfx/tohomon/wynaut/anim_idle.asm"
MurasaAnimationExtra:    INCLUDE "gfx/tohomon/ambipom/anim_idle.asm"
AMurasaAnimationExtra:  INCLUDE "gfx/tohomon/mismagius/anim_idle.asm"
CShouAnimationExtra:  INCLUDE "gfx/tohomon/honchkrow/anim_idle.asm"
ShouAnimationExtra:     INCLUDE "gfx/tohomon/bonsly/anim_idle.asm"
AShouAnimationExtra:     INCLUDE "gfx/tohomon/mime_jr_/anim_idle.asm"
CByakurenAnimationExtra:    INCLUDE "gfx/tohomon/happiny/anim_idle.asm"
ByakurenAnimationExtra:   INCLUDE "gfx/tohomon/munchlax/anim_idle.asm"
TByakurenAnimationExtra:    INCLUDE "gfx/tohomon/mantyke/anim_idle.asm"
CNueAnimationExtra:    INCLUDE "gfx/tohomon/weavile/anim_idle.asm"
NueAnimationExtra:  INCLUDE "gfx/tohomon/magnezone/anim_idle.asm"
SNueAnimationExtra: INCLUDE "gfx/tohomon/lickilicky/anim_idle.asm"
CHatateAnimationExtra:  INCLUDE "gfx/tohomon/rhyperior/anim_idle.asm"
HatateAnimationExtra:  INCLUDE "gfx/tohomon/tangrowth/anim_idle.asm"
THatateAnimationExtra: INCLUDE "gfx/tohomon/electivire/anim_idle.asm"
CSunnyAnimationExtra:  INCLUDE "gfx/tohomon/magmortar/anim_idle.asm"
SunnyAnimationExtra:   INCLUDE "gfx/tohomon/togekiss/anim_idle.asm"
ASunnyAnimationExtra:    INCLUDE "gfx/tohomon/yanmega/anim_idle.asm"
CStarAnimationExtra:    INCLUDE "gfx/tohomon/leafeon/anim_idle.asm"
StarAnimationExtra:    INCLUDE "gfx/tohomon/glaceon/anim_idle.asm"
AMomijiAnimationExtra:    INCLUDE "gfx/tohomon/amomiji/anim_idle.asm"
DStarAnimationExtra:  INCLUDE "gfx/tohomon/mamoswine/anim_idle.asm"
CLunaAnimationExtra:   INCLUDE "gfx/tohomon/clunasa_z/anim_idle.asm"
LunaAnimationExtra:    INCLUDE "gfx/tohomon/sylveon/anim_idle.asm"
TLunaAnimationExtra: INCLUDE "gfx/tohomon/perrserker/anim_idle.asm"
CKyoukoAnimationExtra:    INCLUDE "gfx/tohomon/cursola/anim_idle.asm"
KyoukoAnimationExtra:  INCLUDE "gfx/tohomon/sirfetch_d/anim_idle.asm"
CYoshikaAnimationExtra:     INCLUDE "gfx/tohomon/mr__rime/anim_idle.asm"
YoshikaAnimationExtra:    INCLUDE "gfx/tohomon/wyrdeer/anim_idle.asm"
CSeigaAnimationExtra:    INCLUDE "gfx/tohomon/kleavor/anim_idle.asm"
CTojikoAnimationExtra:   INCLUDE "gfx/tohomon/sneasler/anim_idle.asm"
TojikoAnimationExtra:   INCLUDE "gfx/tohomon/overqwil/anim_idle.asm"
MikoAnimationExtra:  INCLUDE "gfx/tohomon/farigiraf/anim_idle.asm"
FutoAnimationExtra:   INCLUDE "gfx/tohomon/clodsire/anim_idle.asm"
CMikoAnimationExtra: INCLUDE "gfx/tohomon/annihilape/anim_idle.asm"

EggAnimationExtra:        INCLUDE "gfx/tohomon/egg/anim_idle.asm"

HinaAAnimationExtra: INCLUDE "gfx/tohomon/hina_a/anim_idle.asm"
HinaBAnimationExtra: INCLUDE "gfx/tohomon/hina_b/anim_idle.asm"
HinaCAnimationExtra: INCLUDE "gfx/tohomon/hina_c/anim_idle.asm"
HinaDAnimationExtra: INCLUDE "gfx/tohomon/hina_d/anim_idle.asm"
HinaEAnimationExtra: INCLUDE "gfx/tohomon/hina_e/anim_idle.asm"
HinaFAnimationExtra: INCLUDE "gfx/tohomon/hina_f/anim_idle.asm"
HinaGAnimationExtra: INCLUDE "gfx/tohomon/hina_g/anim_idle.asm"
HinaHAnimationExtra: INCLUDE "gfx/tohomon/hina_h/anim_idle.asm"
HinaIAnimationExtra: INCLUDE "gfx/tohomon/hina_i/anim_idle.asm"
HinaJAnimationExtra: INCLUDE "gfx/tohomon/hina_j/anim_idle.asm"
HinaKAnimationExtra: INCLUDE "gfx/tohomon/hina_k/anim_idle.asm"
HinaLAnimationExtra: INCLUDE "gfx/tohomon/hina_l/anim_idle.asm"
HinaMAnimationExtra: INCLUDE "gfx/tohomon/hina_m/anim_idle.asm"
HinaNAnimationExtra: INCLUDE "gfx/tohomon/hina_n/anim_idle.asm"
HinaOAnimationExtra: INCLUDE "gfx/tohomon/hina_o/anim_idle.asm"
HinaPAnimationExtra: INCLUDE "gfx/tohomon/hina_p/anim_idle.asm"
HinaQAnimationExtra: INCLUDE "gfx/tohomon/hina_q/anim_idle.asm"
HinaRAnimationExtra: INCLUDE "gfx/tohomon/hina_r/anim_idle.asm"
HinaSAnimationExtra: INCLUDE "gfx/tohomon/hina_s/anim_idle.asm"
HinaTAnimationExtra: INCLUDE "gfx/tohomon/hina_t/anim_idle.asm"
HinaUAnimationExtra: INCLUDE "gfx/tohomon/hina_u/anim_idle.asm"
HinaVAnimationExtra: INCLUDE "gfx/tohomon/hina_v/anim_idle.asm"
HinaWAnimationExtra: INCLUDE "gfx/tohomon/hina_w/anim_idle.asm"
HinaXAnimationExtra: INCLUDE "gfx/tohomon/hina_x/anim_idle.asm"
HinaYAnimationExtra: INCLUDE "gfx/tohomon/hina_y/anim_idle.asm"
HinaZAnimationExtra: INCLUDE "gfx/tohomon/hina_z/anim_idle.asm"
HinaExclamationAnimationExtra: INCLUDE "gfx/tohomon/hina_exclamation/anim_idle.asm"
HinaQuestionAnimationExtra:    INCLUDE "gfx/tohomon/hina_question/anim_idle.asm"

TTeiAnimationExtra: INCLUDE "gfx/tohomon/ttei/anim_idle.asm"
TTeiSpikyAnimationExtra: INCLUDE "gfx/tohomon/ttei_spiky/anim_idle.asm"

KikuriJohtoAnimationExtra:  INCLUDE "gfx/tohomon/kikuri_johto/anim_idle.asm"
KikuriKantoAnimationExtra:  INCLUDE "gfx/tohomon/kikuri_kanto/anim_idle.asm"
KikuriKogaAnimationExtra:   INCLUDE "gfx/tohomon/kikuri_koga/anim_idle.asm"
KikuriAgathaAnimationExtra: INCLUDE "gfx/tohomon/kikuri_agatha/anim_idle.asm"
KikuriArianaAnimationExtra: INCLUDE "gfx/tohomon/kikuri_ariana/anim_idle.asm"

LilyBlackAnimationExtra: INCLUDE "gfx/tohomon/lilyblack/anim_idle.asm"

CFutoTwoSegmentAnimationExtra:   INCLUDE "gfx/tohomon/placethm_two_segment/anim_idle.asm"
CFutoThreeSegmentAnimationExtra: INCLUDE "gfx/tohomon/placethm_three_segment/anim_idle.asm"

SLilyBlackAnimationExtra: INCLUDE "gfx/tohomon/slilyblack/anim_idle.asm"
SLilyBlackRedAnimationExtra:   INCLUDE "gfx/tohomon/slilyblack_red/anim_idle.asm"

SuikaAnimationExtra:   INCLUDE "gfx/tohomon/suika/anim_idle.asm"
SuikaArmoredAnimationExtra: INCLUDE "gfx/tohomon/suika_armored/anim_idle.asm"

CElisAnimationExtra:  INCLUDE "gfx/tohomon/celis/anim_idle.asm"

CSarielAnimationExtra:  INCLUDE "gfx/tohomon/csariel/anim_idle.asm"

SarielAnimationExtra:  INCLUDE "gfx/tohomon/sariel/anim_idle.asm"

CEllenAnimationExtra:  INCLUDE "gfx/tohomon/cellen/anim_idle.asm"

CChiyuriAnimationExtra:  INCLUDE "gfx/tohomon/cchiyuri/anim_idle.asm"

ChiyuriAnimationExtra:  INCLUDE "gfx/tohomon/chiyuri/anim_idle.asm"

CYumemiAnimationExtra:  INCLUDE "gfx/tohomon/cyumemi/anim_idle.asm"

CSaraAnimationExtra:  INCLUDE "gfx/tohomon/csara/anim_idle.asm"

SaraAnimationExtra:  INCLUDE "gfx/tohomon/sara/anim_idle.asm"

CYumekoAnimationExtra:  INCLUDE "gfx/tohomon/cyumeko/anim_idle.asm"

SCirnoAnimationExtra:  INCLUDE "gfx/tohomon/scirno/anim_idle.asm"

MeilingAnimationExtra:  INCLUDE "gfx/tohomon/meiling/anim_idle.asm"

CLuizeAnimationExtra:    INCLUDE "gfx/tohomon/cluize/anim_idle.asm"

LuizeAnimationExtra:    INCLUDE "gfx/tohomon/luize/anim_idle.asm"

DLuizeAnimationExtra:   INCLUDE "gfx/tohomon/dluize/anim_idle.asm"

CAliceAnimationExtra:    INCLUDE "gfx/tohomon/calice/anim_idle.asm"

CMaiAnimationExtra:     INCLUDE "gfx/tohomon/cmai/anim_idle.asm"

CPatchouliAnimationExtra:    INCLUDE "gfx/tohomon/cpatchouli/anim_idle.asm"

CChenAnimationExtra:    INCLUDE "gfx/tohomon/cchen/anim_idle.asm"

RanAnimationExtra:    INCLUDE "gfx/tohomon/ran/anim_idle.asm"

TRanAnimationExtra:    INCLUDE "gfx/tohomon/tran/anim_idle.asm"

CYukariAnimationExtra:    INCLUDE "gfx/tohomon/cyukari/anim_idle.asm"

HMinorikoAnimationExtra:    INCLUDE "gfx/tohomon/hminoriko/anim_idle.asm"

DKisumeAnimationExtra:    INCLUDE "gfx/tohomon/dkisume/anim_idle.asm"

CKurumiAnimationExtra:   INCLUDE "gfx/tohomon/ckurumi/anim_idle.asm"

DDaichanAnimationExtra:   INCLUDE "gfx/tohomon/ddaichan/anim_idle.asm"

CCirnoAnimationExtra:   INCLUDE "gfx/tohomon/ccirno/anim_idle.asm"

TReisenAnimationExtra:   INCLUDE "gfx/tohomon/treisen/anim_idle.asm"

CSuwakoAnimationExtra:   INCLUDE "gfx/tohomon/csuwako/anim_idle.asm"

IkuAnimationExtra:   INCLUDE "gfx/tohomon/iku/anim_idle.asm"

CShizuhaAnimationExtra:   INCLUDE "gfx/tohomon/cshizuha/anim_idle.asm"

CLilyBlackAnimationExtra:        INCLUDE "gfx/tohomon/clilyblack/anim_idle.asm"

SeigaAnimationExtra:   INCLUDE "gfx/tohomon/ursaluna_plain/anim_idle.asm"