AnimationExtraPointers:
	table_width 2
	dw CReimuAnimationExtra
	dw ReimuAnimationExtra
	dw TReimuAnimationExtra
	dw CMarisaAnimationExtra
	dw MarisaAnimationExtra
	dw AMarisaAnimationExtra
	dw CSakuyaAnimationExtra
	dw SakuyaAnimationExtra
	dw HSakuyaAnimationExtra
	dw CGyokuAnimationExtra
	dw MGyokuAnimationExtra
	dw FGyokuAnimationExtra
	dw OGyokuAnimationExtra
	dw CMaganAnimationExtra
	dw MaganAnimationExtra
	dw CMimaAnimationExtra
	dw MimaAnimationExtra
	dw CElisAnimationExtra
	dw ElisAnimationExtra
	dw CKikuriAnimationExtra
	dw KikuriJohtoAnimationExtra
	dw CSarielAnimationExtra
	dw SarielAnimationExtra
	dw CKongaraAnimationExtra
	dw KongaraAnimationExtra
	dw CRikaAnimationExtra
	dw RikaAnimationExtra
	dw ARikaAnimationExtra
	dw CMeiraAnimationExtra
	dw MeiraAnimationExtra
	dw CEllenAnimationExtra
	dw EllenAnimationExtra
	dw CKotohimeAnimationExtra
	dw KotohimeAnimationExtra
	dw CKanaAnimationExtra
	dw KanaAnimationExtra
	dw CRikakoAnimationExtra
	dw RikakoAnimationExtra
	dw CChiyuriAnimationExtra
	dw ChiyuriAnimationExtra
	dw CYumemiAnimationExtra
	dw YumemiAnimationExtra
	dw COrangeAnimationExtra
	dw OrangeAnimationExtra
	dw CKurumiAnimationExtra
	dw KurumiAnimationExtra
	dw CEllyAnimationExtra
	dw EllyAnimationExtra
	dw CYukaAnimationExtra
	dw YukaAnimationExtra
	dw AYukaAnimationExtra
	dw CMugetsuAnimationExtra
	dw MugetsuAnimationExtra
	dw CGengetsuAnimationExtra
	dw GengetsuAnimationExtra
	dw CSaraAnimationExtra
	dw SaraAnimationExtra
	dw CLuizeAnimationExtra
	dw LuizeAnimationExtra
	dw DLuizeAnimationExtra
	dw CAliceAnimationExtra
	dw AliceAnimationExtra
	dw AAliceAnimationExtra
	dw CMaiAnimationExtra
	dw MaiAnimationExtra
	dw CYukiAnimationExtra
	dw YukiAnimationExtra
	dw CYumekoAnimationExtra
	dw YumekoAnimationExtra
	dw CShinkiAnimationExtra
	dw ShinkiAnimationExtra
	dw CRumiaAnimationExtra
	dw RumiaAnimationExtra
	dw ARumiaAnimationExtra
	dw CDaichanAnimationExtra
	dw DaichanAnimationExtra
	dw DDaichanAnimationExtra
	dw CCirnoAnimationExtra
	dw CirnoAnimationExtra
	dw SCirnoAnimationExtra
	dw CMeilingAnimationExtra
	dw MeilingAnimationExtra
	dw AMeilingAnimationExtra
	dw CKoakumaAnimationExtra
	dw KoakumaAnimationExtra
	dw HKoakumaAnimationExtra
	dw CPatchouliAnimationExtra
	dw PatchouliAnimationExtra
	dw TPatchouliAnimationExtra
	dw CRemiliaAnimationExtra
	dw RemiliaAnimationExtra
	dw SRemiliaAnimationExtra
	dw CFlandreAnimationExtra
	dw FlandreAnimationExtra
	dw AFlandreAnimationExtra
	dw CLettyAnimationExtra
	dw LettyAnimationExtra
	dw DLettyAnimationExtra
	dw CChenAnimationExtra
	dw ChenAnimationExtra
	dw HChenAnimationExtra
	dw CLilyWhiteAnimationExtra
	dw LilyWhiteAnimationExtra
	dw DLilyWhiteAnimationExtra
	dw CLilyBlackAnimationExtra
	dw LilyBlackAnimationExtra
	dw SLilyBlackAnimationExtra
	dw CLyricaAnimationExtra
	dw LyricaAnimationExtra
	dw TLyricaAnimationExtra
	dw CMerlinAnimationExtra
	dw MerlinAnimationExtra
	dw SMerlinAnimationExtra
	dw CLunasaAnimationExtra
	dw LunasaAnimationExtra
	dw ALunasaAnimationExtra
	dw CYuyukoAnimationExtra
	dw YuyukoAnimationExtra
	dw AYuyukoAnimationExtra
	dw CRanAnimationExtra
	dw RanAnimationExtra
	dw TRanAnimationExtra
	dw CYukariAnimationExtra
	dw YukariAnimationExtra
	dw TYukariAnimationExtra
	dw CSuikaAnimationExtra
	dw SuikaAnimationExtra
	dw TSuikaAnimationExtra
	dw CYoumuAnimationExtra
	dw YoumuAnimationExtra
	dw SYoumuAnimationExtra
	dw CReisenAnimationExtra
	dw ReisenAnimationExtra
	dw TReisenAnimationExtra
	dw CSanaeAnimationExtra
	dw SanaeAnimationExtra
	dw DSanaeAnimationExtra
	dw CWriggleAnimationExtra
	dw WriggleAnimationExtra
	dw SWriggleAnimationExtra
	dw CMystiaAnimationExtra
	dw MystiaAnimationExtra
	dw TMystiaAnimationExtra
	dw CKeineAnimationExtra
	dw KeineAnimationExtra
	dw AKeineAnimationExtra
	dw CTeiAnimationExtra
	dw TeiAnimationExtra
	dw TTeiAnimationExtra
	dw CEirinAnimationExtra
	dw EirinAnimationExtra
	dw TEirinAnimationExtra
	dw CKaguyaAnimationExtra
	dw KaguyaAnimationExtra
	dw TKaguyaAnimationExtra
	dw CMokouAnimationExtra
	dw MokouAnimationExtra
	dw AMokouAnimationExtra
	dw CAyaAnimationExtra
	dw AyaAnimationExtra
	dw SAyaAnimationExtra
	dw CMedicineAnimationExtra
	dw MedicineAnimationExtra
	dw AMedicineAnimationExtra
	dw CKomachiAnimationExtra
	dw KomachiAnimationExtra
	dw AKomachiAnimationExtra
	dw CEikiAnimationExtra
	dw EikiAnimationExtra
	dw AEikiAnimationExtra
	dw CShizuhaAnimationExtra
	dw ShizuhaAnimationExtra
	dw SShizuhaAnimationExtra
	dw CMinorikoAnimationExtra
	dw MinorikoAnimationExtra
	dw HMinorikoAnimationExtra
	dw CHinaAnimationExtra
	dw CNueAAnimationExtra
	dw AHinaAnimationExtra
	dw CNitoriAnimationExtra
	dw NitoriAnimationExtra
	dw ANitoriAnimationExtra
	dw CMomijiAnimationExtra
	dw MomijiAnimationExtra
	dw AMomijiAnimationExtra
	dw CKanakoAnimationExtra
	dw KanakoAnimationExtra
	dw AKanakoAnimationExtra
	dw CSuwakoAnimationExtra
	dw SuwakoAnimationExtra
	dw DSuwakoAnimationExtra
	dw CIkuAnimationExtra
	dw IkuAnimationExtra
	dw AIkuAnimationExtra
	dw CTenshiAnimationExtra
	dw TenshiAnimationExtra
	dw STenshiAnimationExtra
	dw CKisumeAnimationExtra
	dw KisumeAnimationExtra
	dw DKisumeAnimationExtra
	dw CYamameAnimationExtra
	dw YamameAnimationExtra
	dw SYamameAnimationExtra
	dw CParseeAnimationExtra
	dw ParseeAnimationExtra
	dw DParseeAnimationExtra
	dw CYuugiAnimationExtra
	dw YuugiAnimationExtra
	dw AYuugiAnimationExtra
	dw CSatoriAnimationExtra
	dw SatoriAnimationExtra
	dw HSatoriAnimationExtra
	dw CRinAnimationExtra
	dw RinAnimationExtra
	dw HRinAnimationExtra
	dw CUtsuhoAnimationExtra
	dw UtsuhoAnimationExtra
	dw AUtsuhoAnimationExtra
	dw CKoishiAnimationExtra
	dw KoishiAnimationExtra
	dw SKoishiAnimationExtra
	dw CNazrinAnimationExtra
	dw NazrinAnimationExtra
	dw HNazrinAnimationExtra
	dw CKogasaAnimationExtra
	dw KogasaAnimationExtra
	dw TKogasaAnimationExtra
	dw CIchirinAnimationExtra
	dw IchirinAnimationExtra
	dw AIchirinAnimationExtra
	dw CMurasaAnimationExtra
	dw MurasaAnimationExtra
	dw EggAnimationExtra
	dw EggAnimationExtra ; $100
	dw AMurasaAnimationExtra
	dw CShouAnimationExtra
	dw ShouAnimationExtra
	dw AShouAnimationExtra
	dw CByakurenAnimationExtra
	dw ByakurenAnimationExtra
	dw TByakurenAnimationExtra
	dw HinaAnimationExtra
	dw NueAnimationExtra
	dw SNueAnimationExtra
	dw CHatateAnimationExtra
	dw HatateAnimationExtra
	dw THatateAnimationExtra
	dw CSunnyAnimationExtra
	dw SunnyAnimationExtra
	dw ASunnyAnimationExtra
	dw CStarAnimationExtra
	dw StarAnimationExtra
	dw DStarAnimationExtra
	dw CLunaAnimationExtra
	dw LunaAnimationExtra
	dw TLunaAnimationExtra
	dw CKyoukoAnimationExtra
	dw KyoukoAnimationExtra
	dw CYoshikaAnimationExtra
	dw YoshikaAnimationExtra
	dw CSeigaAnimationExtra
	dw SeigaAnimationExtra
	dw CTojikoAnimationExtra
	dw TojikoAnimationExtra
	dw CFutoTwoSegmentAnimationExtra
	dw MikoAnimationExtra
	dw FutoAnimationExtra
	dw CMikoAnimationExtra
	dw CMamizouAnimationExtra
	dw MamizouAnimationExtra
	dw CKokoroAnimationExtra
	dw KokoroAnimationExtra
	dw CWakasagiAnimationExtra
	dw WakasagiAnimationExtra
	dw CSekibakiAnimationExtra
	dw SekibakiAnimationExtra
	dw CKagerouAnimationExtra
	dw KagerouAnimationExtra
	dw CBenbenAnimationExtra
	dw BenbenAnimationExtra
	dw CYatsuhaAnimationExtra
	dw YatsuhaAnimationExtra
	dw CSeijaAnimationExtra
	dw SeijaAnimationExtra
	dw CSukunaAnimationExtra
	dw SukunaAnimationExtra
	dw CRaikoAnimationExtra
	dw RaikoAnimationExtra
	dw CKasenAnimationExtra
	dw KasenAnimationExtra
	dw CSumirekoAnimationExtra
	dw SumirekoAnimationExtra
	assert_table_length NUM_SPECIES

	dw CNueBAnimationExtra
	dw CNueCAnimationExtra
	dw CNueDAnimationExtra
	dw CNueEAnimationExtra
	dw CNueFAnimationExtra
	dw CNueGAnimationExtra
	dw CNueHAnimationExtra
	dw CNueIAnimationExtra
	dw CNueJAnimationExtra
	dw CNueKAnimationExtra
	dw CNueLAnimationExtra
	dw CNueMAnimationExtra
	dw CNueNAnimationExtra
	dw CNueOAnimationExtra
	dw CNuePAnimationExtra
	dw CNueQAnimationExtra
	dw CNueRAnimationExtra
	dw CNueSAnimationExtra
	dw CNueTAnimationExtra
	dw CNueUAnimationExtra
	dw CNueVAnimationExtra
	dw CNueWAnimationExtra
	dw CNueXAnimationExtra
	dw CNueYAnimationExtra
	dw CNueZAnimationExtra
	dw CNueExclamationAnimationExtra
	dw CNueQuestionAnimationExtra

	dw KikuriKantoAnimationExtra
	dw KikuriKogaAnimationExtra
	dw KikuriAgathaAnimationExtra
	dw KikuriArianaAnimationExtra


	dw TTeiSpikyAnimationExtra

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedAnimationExtra

	dw SuikaArmoredAnimationExtra

	dw CFutoThreeSegmentAnimationExtra

	assert_table_length NUM_UNIQUE_TOHOMON
