Footprints:: ; needed for BANK(Footprints)

BlankFootprint::
CYuyukoFootprint::
CKeineFootprint::
CGyokuFootprint::
OGyokuFootprint::
LettyFootprint::
DLettyFootprint::
CLunaFootprint::
CMinorikoFootprint::
CStarFootprint::
StarFootprint::
ElisFootprint::
DKisumeFootprint::
CKyoukoFootprint:: 
KikuriFootprint::
CAyaFootprint::
CTeiFootprint::
AKeineFootprint::
YukiFootprint::
CChiyuriFootprint::
LyricaFootprint::
TYukariFootprint::
YukariFootprint::
CFutoFootprint::
ChiyuriFootprint::
CMomijiFootprint::
CKikuriFootprint::
CCirnoFootprint::
CirnoFootprint::
ANitoriFootprint::
CShinkiFootprint::
CSaraFootprint::
AFlandreFootprint::
SLilyBlackFootprint::
ShinkiFootprint::
CFlandreFootprint::
HChenFootprint::
CMaganFootprint::
YuugiFootprint::
HKoakumaFootprint::
TeiFootprint::
CLyricaFootprint::
STenshiFootprint::
LilyBlackFootprint::
NueFootprint::
CParseeFootprint::
TByakurenFootprint::
MGyokuFootprint::
CHinaFootprint::
AMurasaFootprint::
CYumekoFootprint::
CRumiaFootprint::
TojikoFootprint::
NitoriFootprint::
CKogasaFootprint::
CSuwakoFootprint::
CYamameFootprint::
FlandreFootprint::
CLettyFootprint::
CYukiFootprint::
YumekoFootprint::
TenshiFootprint::
CKanakoFootprint::
CEikiFootprint::
GengetsuFootprint::
HinaFootprint::
CGengetsuFootprint::
DDaichanFootprint::
CPatchouliFootprint::
CKotohimeFootprint::
CReimuFootprint::
ReimuFootprint::
TReimuFootprint::
CMarisaFootprint::
MarisaFootprint::
AMarisaFootprint::
CSakuyaFootprint::
SakuyaFootprint::
HSakuyaFootprint::
FGyokuFootprint:: 
MaganFootprint::
CMimaFootprint:: 
MimaFootprint::

CElisFootprint::
CSarielFootprint::
SarielFootprint::
CKongaraFootprint::
KongaraFootprint::
CRikaFootprint::
RikaFootprint::
ARikaFootprint::
CMeiraFootprint:: 
MeiraFootprint:: 
CEllenFootprint:: 
EllenFootprint:: 
KotohimeFootprint:: 
CKanaFootprint:: 
KanaFootprint:: 
CRikakoFootprint:: 
RikakoFootprint:: 
CYumemiFootprint:: 
YumemiFootprint:: 
COrangeFootprint:: 
OrangeFootprint:: 
CKurumiFootprint:: 
KurumiFootprint:: 
CEllyFootprint:: 
EllyFootprint:: 
CYukaFootprint:: 
YukaFootprint:: 
AYukaFootprint:: 
CMugetsuFootprint:: 
MugetsuFootprint:: 
SaraFootprint:: 
CLuizeFootprint:: 
LuizeFootprint:: 
DLuizeFootprint:: 
CAliceFootprint:: 
AliceFootprint:: 
AAliceFootprint:: 
CMaiFootprint:: 
MaiFootprint::  
RumiaFootprint:: 
ARumiaFootprint:: 
CDaichanFootprint:: 
DaichanFootprint:: 
SCirnoFootprint:: 
CMeilingFootprint:: 
MeilingFootprint:: 
AMeilingFootprint:: 
CKoakumaFootprint:: 
KoakumaFootprint:: 
PatchouliFootprint:: 
TPatchouliFootprint:: 
CRemiliaFootprint:: 
RemiliaFootprint:: 
SRemiliaFootprint:: 
CChenFootprint:: 
ChenFootprint:: 
CLilyWhiteFootprint:: 
LilyWhiteFootprint:: 
DLilyWhiteFootprint:: 
CLilyBlackFootprint:: 
TLyricaFootprint:: 
CMerlinFootprint:: 
MerlinFootprint:: 
SMerlinFootprint:: 
CLunasaFootprint:: 
LunasaFootprint:: 
ALunasaFootprint:: 
YuyukoFootprint:: 
AYuyukoFootprint:: 
CRanFootprint:: 
RanFootprint:: 
TRanFootprint:: 
CYukariFootprint:: 
CSuikaFootprint:: 
SuikaFootprint:: 
TSuikaFootprint:: 
CYoumuFootprint::
YoumuFootprint:: 
SYoumuFootprint:: 
CReisenFootprint:: 
ReisenFootprint:: 
TReisenFootprint:: 
CSanaeFootprint:: 
SanaeFootprint:: 
DSanaeFootprint:: 
CWriggleFootprint:: 
WriggleFootprint:: 
SWriggleFootprint:: 
CMystiaFootprint:: 
MystiaFootprint:: 
TMystiaFootprint:: 
KeineFootprint:: 
TTeiFootprint:: 
CEirinFootprint:: 
EirinFootprint:: 
TEirinFootprint:: 
CKaguyaFootprint:: 
KaguyaFootprint:: 
TKaguyaFootprint:: 
CMokouFootprint:: 
MokouFootprint:: 
AMokouFootprint:: 
AyaFootprint:: 
SAyaFootprint::
CMedicineFootprint::
MedicineFootprint::
AMedicineFootprint:: 
CKomachiFootprint::
KomachiFootprint::
AKomachiFootprint::
EikiFootprint::
AEikiFootprint::
CShizuhaFootprint::
ShizuhaFootprint::
SShizuhaFootprint::
MinorikoFootprint::
HMinorikoFootprint::
AHinaFootprint:: 
CNitoriFootprint::
MomijiFootprint::
KanakoFootprint::
AKanakoFootprint::
SuwakoFootprint::
DSuwakoFootprint:: 
CIkuFootprint::
IkuFootprint::
AIkuFootprint::
CTenshiFootprint::
CKisumeFootprint::
KisumeFootprint::
YamameFootprint::
SYamameFootprint:: 
ParseeFootprint::
DParseeFootprint::
CYuugiFootprint::
AYuugiFootprint::
CSatoriFootprint::
SatoriFootprint:: 
HSatoriFootprint::
CRinFootprint:: 
RinFootprint:: 
HRinFootprint:: 
CUtsuhoFootprint:: 
UtsuhoFootprint::
AUtsuhoFootprint:: 
CKoishiFootprint::
KoishiFootprint::
SKoishiFootprint::
CNazrinFootprint::
NazrinFootprint::
HNazrinFootprint::
KogasaFootprint::
TKogasaFootprint:: 
CIchirinFootprint:: 
IchirinFootprint::
AIchirinFootprint::
CMurasaFootprint::
MurasaFootprint::
EggFootprint::
CShouFootprint::
ShouFootprint:: 
AShouFootprint::
CByakurenFootprint::
ByakurenFootprint::
CNueFootprint::
SNueFootprint::
CHatateFootprint::
HatateFootprint:: 
THatateFootprint::
CSunnyFootprint::
SunnyFootprint::
ASunnyFootprint::
AMomijiFootprint::
DStarFootprint::
LunaFootprint::
TLunaFootprint::
KyoukoFootprint::
CYoshikaFootprint::
YoshikaFootprint::
CSeigaFootprint::
SeigaFootprint::
CTojikoFootprint:: 
MikoFootprint::
FutoFootprint:: 
CMikoFootprint::
CMamizouFootprint:: 
MamizouFootprint:: 
CKokoroFootprint:: 
KokoroFootprint:: 
CWakasagiFootprint:: 
WakasagiFootprint::
CSekibakiFootprint:: 
SekibakiFootprint:: 
CKagerouFootprint:: 
KagerouFootprint:: 
CBenbenFootprint::
BenbenFootprint:: 
CYatsuhaFootprint::   
YatsuhaFootprint:: 
CSeijaFootprint::
SeijaFootprint::
CSukunaFootprint::
SukunaFootprint::
CRaikoFootprint::
RaikoFootprint::
CKasenFootprint::
KasenFootprint::
CSumirekoFootprint::
SumirekoFootprint:: INCBIN "gfx/footprints/blank.1bpp.lz"         