FramesPointers:
	table_width 2
	dw CReimuFrames
	dw ReimuFrames
	dw TReimuFrames
	dw CMarisaFrames
	dw MarisaFrames
	dw AMarisaFrames
	dw CSakuyaFrames
	dw SakuyaFrames
	dw HSakuyaFrames
	dw CGyokuFrames
	dw MGyokuFrames
	dw FGyokuFrames
	dw OGyokuFrames
	dw CMaganFrames
	dw MaganFrames
	dw CMimaFrames
	dw MimaFrames
	dw CElisFrames
	dw ElisFrames
	dw CKikuriFrames
	dw KikuriJohtoFrames
	dw CSarielFrames
	dw SarielFrames
	dw CKongaraFrames
	dw KongaraFrames
	dw CRikaFrames
	dw RikaFrames
	dw ARikaFrames
	dw CMeiraFrames
	dw MeiraFrames
	dw CEllenFrames
	dw EllenFrames
	dw CKotohimeFrames
	dw KotohimeFrames
	dw CKanaFrames
	dw KanaFrames
	dw CRikakoFrames
	dw RikakoFrames
	dw CChiyuriFrames
	dw ChiyuriFrames
	dw CYumemiFrames
	dw YumemiFrames
	dw COrangeFrames
	dw OrangeFrames
	dw CKurumiFrames
	dw KurumiFrames
	dw CEllyFrames
	dw EllyFrames
	dw CYukaFrames
	dw YukaFrames
	dw AYukaFrames
	dw CMugetsuFrames
	dw MugetsuFrames
	dw CGengetsuFrames
	dw GengetsuFrames
	dw CSaraFrames
	dw SaraFrames
	dw CLuizeFrames
	dw LuizeFrames
	dw DLuizeFrames
	dw CAliceFrames
	dw AliceFrames
	dw AAliceFrames
	dw CMaiFrames
	dw MaiFrames
	dw CYukiFrames
	dw YukiFrames
	dw CYumekoFrames
	dw YumekoFrames
	dw CShinkiFrames
	dw ShinkiFrames
	dw CRumiaFrames
	dw RumiaFrames
	dw ARumiaFrames
	dw CDaichanFrames
	dw DaichanFrames
	dw DDaichanFrames
	dw CCirnoFrames
	dw CirnoFrames
	dw SCirnoFrames
	dw CMeilingFrames
	dw MeilingFrames
	dw AMeilingFrames
	dw CKoakumaFrames
	dw KoakumaFrames
	dw HKoakumaFrames
	dw CPatchouliFrames
	dw PatchouliFrames
	dw TPatchouliFrames
	dw CRemiliaFrames
	dw RemiliaFrames
	dw SRemiliaFrames
	dw CFlandreFrames
	dw FlandreFrames
	dw AFlandreFrames
	dw CLettyFrames
	dw LettyFrames
	dw DLettyFrames
	dw CChenFrames
	dw ChenFrames
	dw HChenFrames
	dw CLilyWhiteFrames
	dw LilyWhiteFrames
	dw DLilyWhiteFrames
	dw CLilyBlackFrames
	dw LilyBlackFrames
	dw SLilyBlackFrames
	dw CLyricaFrames
	dw LyricaFrames
	dw TLyricaFrames
	dw CMerlinFrames
	dw MerlinFrames
	dw SMerlinFrames
	dw CLunasaFrames
	dw LunasaFrames
	dw ALunasaFrames
	dw CYuyukoFrames
	dw YuyukoFrames
	dw AYuyukoFrames
	dw CRanFrames
	dw RanFrames
	dw TRanFrames
	dw CYukariFrames
	dw YukariFrames
	dw TYukariFrames
	dw CSuikaFrames
	dw SuikaFrames
	dw TSuikaFrames
	dw CYoumuFrames
	dw YoumuFrames
	dw SYoumuFrames
	dw CReisenFrames
	dw ReisenFrames
	dw TReisenFrames
	dw CSanaeFrames
	dw SanaeFrames
	dw DSanaeFrames
	dw CWriggleFrames
	dw WriggleFrames
	dw SWriggleFrames
	dw CMystiaFrames
	dw MystiaFrames
	dw TMystiaFrames
	dw CKeineFrames
	dw KeineFrames
	dw AKeineFrames
	dw CTeiFrames
	dw TeiFrames
	dw TTeiFrames
	dw CEirinFrames
	dw EirinFrames
	dw TEirinFrames
	dw CKaguyaFrames
	dw KaguyaFrames
	dw TKaguyaFrames
	dw CMokouFrames
	dw MokouFrames
	dw AMokouFrames
	dw CAyaFrames
	dw AyaFrames
	dw SAyaFrames
	dw CMedicineFrames
	dw MedicineFrames
	dw AMedicineFrames
	dw CKomachiFrames
	dw KomachiFrames
	dw AKomachiFrames
	dw CEikiFrames
	dw EikiFrames
	dw AEikiFrames
	dw CShizuhaFrames
	dw ShizuhaFrames
	dw SShizuhaFrames
	dw CMinorikoFrames
	dw MinorikoFrames
	dw HMinorikoFrames
	dw CHinaFrames
	dw CNueAFrames
	dw AHinaFrames
	dw CNitoriFrames
	dw NitoriFrames
	dw ANitoriFrames
	dw CMomijiFrames
	dw MomijiFrames
	dw CKanakoFrames
	dw KanakoFrames
	dw AKanakoFrames
	dw CSuwakoFrames
	dw SuwakoFrames
	dw DSuwakoFrames
	dw CIkuFrames
	dw IkuFrames
	dw AIkuFrames
	dw CTenshiFrames
	dw TenshiFrames
	dw STenshiFrames
	dw CKisumeFrames
	dw KisumeFrames
	dw DKisumeFrames
	dw CYamameFrames
	dw YamameFrames
	dw SYamameFrames
	dw CParseeFrames
	dw ParseeFrames
	dw DParseeFrames
	dw CYuugiFrames
	dw YuugiFrames
	dw AYuugiFrames
	dw CSatoriFrames
	dw SatoriFrames
	dw HSatoriFrames
	dw CRinFrames
	dw RinFrames
	dw HRinFrames
	dw CUtsuhoFrames
	dw UtsuhoFrames
	dw AUtsuhoFrames
	dw CKoishiFrames
	dw KoishiFrames
	dw SKoishiFrames
	dw CNazrinFrames
	dw NazrinFrames
	dw HNazrinFrames
	dw CKogasaFrames
	dw KogasaFrames
	dw TKogasaFrames
	dw CIchirinFrames
	dw IchirinFrames
	dw AIchirinFrames
	dw CMurasaFrames
	dw MurasaFrames
	dw AMurasaFrames
	dw CShouFrames
	dw ShouFrames
	dw AShouFrames
	dw CByakurenFrames
	dw ByakurenFrames
	dw TByakurenFrames
	dw HinaFrames
	dw NueFrames
	dw SNueFrames
	dw CHatateFrames
	dw HatateFrames
	dw THatateFrames
	dw CSunnyFrames
	dw SunnyFrames
	dw ASunnyFrames
	dw CStarFrames
	dw StarFrames
	dw AMomijiFrames
	dw DStarFrames
	dw CLunaFrames
	dw LunaFrames
	dw TLunaFrames
	dw EggFrames
	dw EggFrames ; $100
	dw CKyoukoFrames
	dw KyoukoFrames
	dw CYoshikaFrames
	dw YoshikaFrames
	dw CSeigaFrames
	dw SeigaFrames
	dw CTojikoFrames
	dw TojikoFrames
	dw CFutoFrames
	dw FutoFrames
	dw CMikoFrames
	dw MikoFrames
	dw CMamizouFrames
	dw MamizouFrames
	dw CKokoroFrames
	dw KokoroFrames
	dw CWakasagiFrames
	dw WakasagiFrames
	dw CSekibakiFrames
	dw SekibakiFrames
	dw CKagerouFrames
	dw KagerouFrames
	dw CBenbenFrames
	dw BenbenFrames
	dw CYatsuhaFrames
	dw YatsuhaFrames
	dw CSeijaFrames
	dw SeijaFrames
	dw CSukunaFrames
	dw SukunaFrames
	dw CRaikoFrames
	dw RaikoFrames
	dw CKasenFrames
	dw KasenFrames
	dw CSumirekoFrames
	dw SumirekoFrames
	assert_table_length NUM_SPECIES

	dw CNueBFrames
	dw CNueCFrames
	dw CNueDFrames
	dw CNueEFrames
	dw CNueFFrames
	dw CNueGFrames
	dw CNueHFrames
	dw CNueIFrames
	dw CNueJFrames
	dw CNueKFrames
	dw CNueLFrames
	dw CNueMFrames
	dw CNueNFrames
	dw CNueOFrames
	dw CNuePFrames
	dw CNueQFrames
	dw CNueRFrames
	dw CNueSFrames
	dw CNueTFrames
	dw CNueUFrames
	dw CNueVFrames
	dw CNueWFrames
	dw CNueXFrames
	dw CNueYFrames
	dw CNueZFrames
	dw CNueExclamationFrames
	dw CNueQuestionFrames

	dw KikuriKantoFrames
	dw KikuriKogaFrames
	dw KikuriAgathaFrames
	dw KikuriArianaFrames



	dw TTeiSpikyFrames

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedFrames

	dw SuikaArmoredFrames

	assert_table_length NUM_UNIQUE_TOHOMON
